SCR_MissionHeaderCampaign : "{A1CF190919100000}Missions/AICF_RHS_Conflict_Everon_North.conf"
{
	m_sName "#AICF_Scenario_EveronNorthRHS_Medium_Name"
	m_sDescription "#AICF_Scenario_EveronNorthRHS_Medium_Description"
	m_sDetails "#AICF_Scenario_EveronNorthRHS_Medium_Details"
	m_eAICFDifficulty 1
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
