SCR_MissionHeaderCampaign : "{57FA3D0337BE47E5}Missions/AICF_RHS_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_EveronNorthRHS_Name"
	m_sDescription "#AICF_Scenario_EveronNorthRHS_Description"
	m_sDetails "#AICF_Scenario_EveronNorthRHS_Details"
	m_bCustomBaseWhitelist 1
	m_bEstablishingBasesEnabled 0
	m_aCampaignCustomBaseList
	{
		SCR_CampaignCustomBase "{A1CF190919100001}"
		{
			m_sBaseName "MilitaryBaseAirfield"
			m_fRadioRange 2000
			m_bCanBeHQ 1
		}
		SCR_CampaignCustomBase "{A1CF190919100002}"
		{
			m_sBaseName "MilitaryHospital"
			m_fRadioRange 2000
			m_bCanBeHQ 1
		}
		SCR_CampaignCustomBase "{A1CF190919100003}"
		{
			m_sBaseName "MainBaseNorth"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919100004}"
		{
			m_sBaseName "SmallBaseMaidensBay"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919100005}"
		{
			m_sBaseName "TownBaseMeaux"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919100006}"
		{
			m_sBaseName "TownBaseTyrone"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919100008}"
		{
			m_sBaseName "SmallBaseHornbeamValley"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
	}
}
