SCR_MissionHeaderCampaign : "{57FA3D0337BE47E5}Missions/AICF_RHS_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_EveronRHS_Medium_Name"
	m_sDescription "#AICF_Scenario_EveronRHS_Medium_Description"
	m_sDetails "#AICF_Scenario_EveronRHS_Medium_Details"
	m_eAICFDifficulty 1
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
