SCR_MissionHeaderCampaign : "{BC2437E4861B4FD2}Missions/AICF_Conflict_Arland.conf"
{
	m_sName "#AICF_Scenario_Arland_Hard_Name"
	m_sDescription "#AICF_Scenario_Arland_Hard_Description"
	m_sDetails "#AICF_Scenario_Arland_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
