SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf"
{
	m_sName "#AICF_Scenario_Arland_Name"
	m_sAuthor "AI Conflict"
	m_sDescription "#AICF_Scenario_Arland_Description"
	m_sDetails "#AICF_Scenario_Arland_Details"
	m_sGameMode "AI Conflict"
	m_bShowInScenarioMenu 1
	m_eSaveTypes 0
	m_bIgnoreMinimumVehicleRank 1
	m_eStartingRank GENERAL
	m_bOverrideScenarioTimeAndWeather 1
	m_iStartingHours 8
	m_iStartingMinutes 0
	m_bRandomStartingDaytime 0
	m_fDayTimeAcceleration 6
	m_fNightTimeAcceleration 24
}
