SCR_MissionHeaderCampaign : "{C41618FD18E9D714}Missions/23_Campaign_Arland.conf"
{
	m_sName "AI Conflict - Arland"
	m_sAuthor "AI Conflict"
	m_sDescription "Autonomous US versus USSR Conflict on Arland."
	m_sDetails "Launches AI Conflict on the official Conflict - Arland scenario. Both factions use AI commanders by default."
	m_sGameMode "AI Conflict"
	m_bShowInScenarioMenu 1
	m_bIgnoreMinimumVehicleRank 1
	m_eStartingRank GENERAL
	m_bOverrideScenarioTimeAndWeather 1
	m_fDayTimeAcceleration 6
	m_fNightTimeAcceleration 24
}
