SCR_MissionHeaderCampaign : "{A1CF261006100002}Missions/AICF_WCS_RHS_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_EveronWCSRHS_Hard_Name"
	m_sDescription "#AICF_Scenario_EveronWCSRHS_Hard_Description"
	m_sDetails "#AICF_Scenario_EveronWCSRHS_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
