SCR_MissionHeaderCampaign : "{57FA3D0337BE47E5}Missions/AICF_RHS_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_EveronWCSRHS_Name"
	m_sAuthor "AI Conflict"
	m_sDescription "#AICF_Scenario_EveronWCSRHS_Description"
	m_sDetails "#AICF_Scenario_EveronWCSRHS_Details"
	m_sGameMode "AI Conflict"
	m_bShowInScenarioMenu 1
	m_eSaveTypes 0
}
