SCR_MissionHeaderCampaign : "{A1CF261006100003}Missions/AICF_WCS_RHS_Conflict_Everon_North.conf"
{
	m_sName "#AICF_Scenario_EveronNorthWCSRHS_Medium_Name"
	m_sDescription "#AICF_Scenario_EveronNorthWCSRHS_Medium_Description"
	m_sDetails "#AICF_Scenario_EveronNorthWCSRHS_Medium_Details"
	m_eAICFDifficulty 1
}
