SCR_MissionHeaderCampaign : "{A1CF260928100002}Missions/AICF_WCS_RHS_Conflict_Arland.conf"
{
	m_sName "#AICF_Scenario_ArlandWCSRHS_Hard_Name"
	m_sDescription "#AICF_Scenario_ArlandWCSRHS_Hard_Description"
	m_sDetails "#AICF_Scenario_ArlandWCSRHS_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 1
	m_bAICFFIAPassengers 0
}
