SCR_MissionHeaderCampaign : "{97E4BCB73F044C66}Missions/AICF_RHS_Conflict_Arland.conf"
{
	m_sName "#AICF_Scenario_ArlandRHS_Hard_Name"
	m_sDescription "#AICF_Scenario_ArlandRHS_Hard_Description"
	m_sDetails "#AICF_Scenario_ArlandRHS_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
