SCR_MissionHeaderCampaign : "{7577640CD42A00BD}Missions/RHS_Conflict_Arland.conf"
{
	m_sName "AI Conflict RHS - Arland"
	m_sAuthor "AI Conflict"
	m_sDescription "Autonomous RHS USMC versus RHS MSV Conflict on Arland."
	m_sDetails "Launches AI Conflict on the official RHS Conflict - Arland scenario. Both factions use AI commanders by default."
	m_sGameMode "AI Conflict"
	m_bShowInScenarioMenu 1
	m_bIgnoreMinimumVehicleRank 1
	m_eStartingRank GENERAL
	m_bOverrideScenarioTimeAndWeather 1
	m_fDayTimeAcceleration 6
	m_fNightTimeAcceleration 24
}
