SCR_MissionHeaderCampaign : "{7577640CD42A00BD}Missions/RHS_Conflict_Arland.conf"
{
	m_sName "#AICF_Scenario_ArlandRHS_Name"
	m_sAuthor "AI Conflict"
	m_sDescription "#AICF_Scenario_ArlandRHS_Description"
	m_sDetails "#AICF_Scenario_ArlandRHS_Details"
	m_sGameMode "AI Conflict"
	m_bShowInScenarioMenu 1
	m_eSaveTypes 0
	m_bIgnoreMinimumVehicleRank 1
	m_eStartingRank GENERAL
	m_bOverrideScenarioTimeAndWeather 1
	m_fDayTimeAcceleration 6
	m_fNightTimeAcceleration 24
}
