SCR_MissionHeaderCampaign : "{4C5D73A5614F41D9}Missions/AICF_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_EveronNorth_Name"
	m_sDescription "#AICF_Scenario_EveronNorth_Description"
	m_sDetails "#AICF_Scenario_EveronNorth_Details"
	m_bCustomBaseWhitelist 1
	m_bEstablishingBasesEnabled 0
	m_aCampaignCustomBaseList
	{
		SCR_CampaignCustomBase "{A1CF190919300001}"
		{
			m_sBaseName "MilitaryBaseAirfield"
			m_fRadioRange 2000
			m_bCanBeHQ 1
		}
		SCR_CampaignCustomBase "{A1CF190919300002}"
		{
			m_sBaseName "MilitaryHospital"
			m_fRadioRange 2000
			m_bCanBeHQ 1
		}
		SCR_CampaignCustomBase "{A1CF190919300003}"
		{
			m_sBaseName "MainBaseNorth"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300004}"
		{
			m_sBaseName "SmallBaseMaidensBay"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300005}"
		{
			m_sBaseName "TownBaseMeaux"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300006}"
		{
			m_sBaseName "TownBaseTyrone"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300007}"
		{
			m_sBaseName "TownBaseKermovan"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300008}"
		{
			m_sBaseName "StartingPos06"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
		SCR_CampaignCustomBase "{A1CF190919300009}"
		{
			m_sBaseName "StartingPos12"
			m_fRadioRange 2000
			m_bIsControlPoint 1
		}
	}
}
