SCR_MissionHeaderCampaign : "{A1CF190919300000}Missions/AICF_Conflict_Everon_North.conf"
{
	m_sName "#AICF_Scenario_EveronNorth_Hard_Name"
	m_sDescription "#AICF_Scenario_EveronNorth_Hard_Description"
	m_sDetails "#AICF_Scenario_EveronNorth_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
