SCR_MissionHeaderCampaign : "{4C5D73A5614F41D9}Missions/AICF_Conflict_Everon.conf"
{
	m_sName "#AICF_Scenario_Everon_Hard_Name"
	m_sDescription "#AICF_Scenario_Everon_Hard_Description"
	m_sDetails "#AICF_Scenario_Everon_Hard_Details"
	m_eAICFDifficulty 2
	m_bAICFFIATank 0
	m_bAICFFIAPassengers 0
}
