param([string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Stage3StaticAudit.Common.ps1')
$core = Join-Path $RepositoryRoot 'AIConflictCore/Scripts/Game/AIConflict'
$failures = [Collections.Generic.List[string]]::new()
function Read-Code([string]$path) { Get-Content -LiteralPath (Join-Path $core $path) -Raw }
function Require([string]$rule, [string]$code, [string]$pattern) {
    if ($code -notmatch $pattern) { $failures.Add($rule) }
}
function Forbid([string]$rule, [string]$code, [string]$pattern) {
    if ($code -match $pattern) { $failures.Add($rule) }
}
$config = Read-Code 'Config/AICF_LogisticsConfig.c'
$registry = Read-Code 'Economy/AICF_LogisticsDepotRegistry.c'
$planner = Read-Code 'Economy/AICF_LogisticsPlanner.c'
$ledger = Read-Code 'Economy/AICF_LogisticsLedger.c'
$resource = Read-Code 'Economy/AICF_LogisticsResourcePool.c'
$worker = Read-Code 'Economy/AICF_LogisticsJob.c'
$service = Read-Code 'Economy/AICF_LogisticsService.c'
$acquisitionFlow = Read-Code 'Vehicles/AICF_LogisticsAcquisitionFlow.c'
$acquisition = $acquisitionFlow + (Read-Code 'Vehicles/AICF_VehicleSpawner.c') + (Read-Code 'State/Vehicles/AICF_FactionFleet.c')
$flows = (Read-Code 'Vehicles/AICF_TransportTripController.c') + (Read-Code 'Vehicles/AICF_VehicleTaskHandoff.c')
$cleanup = Read-Code 'Vehicles/AICF_VehicleCleanupManager.c'
$interaction = Read-Code 'Vehicles/AICF_LogisticsDriverInteraction.c'
$driverRecovery = Read-Code 'Vehicles/AICF_LogisticsDriverRecovery.c'
$routeRecovery = Read-Code 'Vehicles/AICF_LogisticsRouteRecovery.c'
$fallback = Read-Code 'Vehicles/AICF_LogisticsFallback.c'
$exitHistory = Read-Code 'Economy/AICF_LogisticsExitHistory.c'
$delete = Read-Code 'Vehicles/AICF_VehicleCleanupManager.c'
$facade = Read-Code 'Economy/AICF_SupplyDeliverySystem.c'
$footprint = Read-Code 'Vehicles/AICF_LogisticsVehicleFootprint.c'
$spawnGeometry = Read-Code 'Vehicles/AICF_LogisticsSpawnGeometry.c'
$spawner = Read-Code 'Vehicles/AICF_VehicleSpawner.c'
function Method([string]$source, [string]$name) {
    Get-AICFMethodBody ([pscustomobject]@{ Source = $source; Code = ConvertTo-AICFCodeText $source }) $name
}
$bodyClear = Method $footprint 'IsClear'
$spawnClear = Method $spawner 'LogisticsSpawnClear'
$reserveSite = Method $spawner 'ReserveLogisticsSite'
$reserveSlot = Method $spawner 'ReserveLogisticsSlot'
$spawnLogistics = Method $spawner 'SpawnLogistics'
$slotClear = Method $registry 'AICF_LogisticsClear'
$candidateSlots = Method $registry 'AICF_LogisticsCandidateSlots'
$fallbackBoarding = Method (Read-Code 'Vehicles/AICF_VehicleBoardingFlow.c') 'TickLogisticsFallback'
$fallbackTransit = Method (Read-Code 'Vehicles/AICF_VehicleTransitFlow.c') 'TickLogisticsFallback'
Require 'FALLBACK_AUTHORITY_IDENTITY' $fallback '!Replication.IsServer\(\) \|\| !Matches\(w\) \|\| w.HasForeignOccupant\(true\)'
Require 'FALLBACK_CARGO_IDENTITY' $fallback 'w.m_CargoPool != m_CargoPool \|\| !m_CargoPool \|\| !m_CargoPool.Valid\(\)'
Require 'FALLBACK_TTL_NOT_RESURRECTED' $fallback 'm_Job && now >= m_Job.m_iExpiresAtMs'
Require 'FALLBACK_BOUNDED_LEG' $fallback 'w.m_iFallbackAttempts >= MAX_PER_LEG'
Require 'FALLBACK_BOUNDED_TIME' $fallback 'now - m_iStartedAtMs >= TIMEOUT_MS'
Require 'FALLBACK_NO_OTHER_VEHICLE' $fallback '!linked \|\| linked == m_Vehicle'
Require 'FALLBACK_NO_OTHER_SEAT' $fallback '!access.GetCompartment\(\) \|\| access.GetCompartment\(\) == m_Seat'
Require 'FALLBACK_EXACT_DRIVER_TELEPORT' $fallbackBoarding 'access.GetInVehicle\(w.m_Seat.GetOwner\(\), w.m_Seat, true,'
Require 'FALLBACK_DRIVER_RECHECK' $fallbackBoarding '!recovery.Safe\(w, System.GetTickCount\(\)\) \|\| w.HasForeignOccupant\(true\)'
Require 'FALLBACK_SEAT_RETRY_BOUND' $fallbackBoarding 'recovery.m_iSeatAttempts >= 3'
Require 'FALLBACK_TRANSFORM_RECHECK' $fallbackTransit '!recovery.Safe\(w, System.GetTickCount\(\)\) \|\| !w.Ready\(\) \|\| w.HasForeignOccupant\(\)'
Require 'FALLBACK_DESTINATION_COLLISION' $fallbackTransit '!footprint.IsClear\(w.m_Vehicle.GetWorld\(\), pose, body\)'
Require 'FALLBACK_CARGO_READBACK' $fallbackTransit 'Math.AbsFloat\(cargoBefore - cargoAfter\) > AICF_LogisticsConfig.RESOURCE_EPSILON'
Require 'FALLBACK_PLAYER_USE' $fallbackTransit '!AICF_LogisticsFallback.PlayersClear\(source, pose\[3\]\)'
Require 'FALLBACK_JUMP_NOT_ARRIVAL' (Read-Code 'Vehicles/AICF_VehicleTransitFlow.c') '!w.m_RouteRecovery.m_bAwaitingRelocationMotion && physics'
Require 'FALLBACK_JUMP_NOT_MOTION' $routeRecovery 'w.m_vProgressPosition = m_vAttemptPosition;'
Forbid 'FALLBACK_NO_ECONOMY_OR_LIFECYCLE' ($fallback + $fallbackBoarding + $fallbackTransit) 'SpawnEntity|DeleteRplEntity|AddSupplies\(|SetResourceValue\(|m_ePhase\s*=|m_Job\s*=|MarkProgress\('
Require 'SPAWN_GEOMETRY_FAIL_CLOSED' $spawnClear '!footprint \|\| !footprint.m_bValid'
Require 'SPAWN_BODY_COLLISION' $spawnClear 'if \(!footprint.IsClear\(world, w.m_aSpawnTransform, body\)\) return RejectLogisticsSite'
Require 'SPAWN_PHYSICS_PENETRATION' $bodyClear '(?s)world.TracePosition\(body, null\).*?return penetration >= 0;'
Require 'SPAWN_BODY_LAYER' $bodyClear 'body.LayerMask = EPhysicsLayerPresets.Vehicle;'
Require 'SPAWN_BODY_MIN_UNPADDED' $bodyClear 'body.Mins = m_vMin;'
Require 'SPAWN_BODY_MAX_UNPADDED' $bodyClear 'body.Maxs = m_vMax;'
Require 'SPAWN_BODY_ORIENTATION' $bodyClear 'body.Mat\[axis\] = transform\[axis\];'
Require 'SPAWN_BODY_EXACT_POSITION' $bodyClear 'body.Start = transform\[3\];'
Forbid 'SPAWN_NO_BROADPHASE_VETO' ($bodyClear + $slotClear + $spawnClear) 'QueryEntitiesBy|GetMinBoundsVector|GetMaxBoundsVector|\.Exclude\s*='
Require 'SPAWN_SLOT_PREFAB_GEOMETRY' $slotClear 'footprint.IsClear\(GetGame\(\).GetWorld\(\), transform, body\)'
Require 'SPAWN_SLOT_PREFAB_IDENTITY' $candidateSlots 'slot.AICF_LogisticsClear\(entry.GetPrefab\(\)\)'
Require 'SPAWN_SURFACE_REJECTION' $spawnClear 'if \(!IsWheeledSpawnSurfaceSuitable\(.*\)\) return RejectLogisticsSite'
Require 'SPAWN_EXIT_COLLISION' $spawnClear '!AICF_LogisticsSpawnGeometry.ExitClear\(world, footprint, w.m_aSpawnTransform, w.m_vSpawnExit, exitTrace\)'
Require 'SPAWN_PARKING_FALLBACK' $spawnClear 'w.m_vParking = w.m_aSpawnTransform\[3\];'
Require 'SPAWN_ROAD_OPTIONAL' $spawnClear 'if \(!ai \|\| !ai.GetRoadNetworkManager\(\)\) return true;'
Require 'SPAWN_CATALOG_ONLY' $reserveSite 'AICF_LogisticsCandidateSlots\(w.m_Entry, candidates, false\)'
Require 'SPAWN_SLOT_TRANSFORM' $reserveSlot 'slot.GetOwner\(\).GetWorldTransform\(w.m_aSlotTransform\);'
Require 'SPAWN_SLOT_REVALIDATED' $spawnClear 'currentTransform\[axis\] != w.m_aSlotTransform\[axis\]'
Require 'SPAWN_SHARED_RESERVATIONS' ($spawnClear + $reserveSlot) '(?s)foreach \(AICF_VehicleSpawnSiteReservation other : s_aConstructionSites\).*?!other.IsExpired.*?return RejectLogisticsSite.*?s_aConstructionSites.Insert\(w.m_Site\);'
Require 'SPAWN_CONSTRUCTION_RESERVATIONS' $spawnClear '!AICF_ConstructionPlanner.VehicleAreaClear\(position, 12\)'
Require 'SPAWN_RESERVE_LIVE_BODY' $reserveSlot 'if \(!LogisticsSpawnClear\(w, false\)\) continue;'
Require 'SPAWN_COMMIT_LIVE_BODY' $spawnLogistics '(?s)!LogisticsSpawnClear\(w\)\) return false;.*?SpawnSelectedPrefab\('
Require 'CONFIG_STRICT_PARSE' $config 'Decimal\(text, false, parsed\)'
Require 'CONFIG_THRESHOLD_ORDER' $config 'm_fTargetPercent <= m_fDonorKeepPercent.*m_fDonorKeepPercent < m_fDonateAbovePercent'
Require 'DEPRECATION_EXPLICIT' $config 'LOGISTICS_CONFIG_DEPRECATED.*ignored=1'
Forbid 'NO_TIMER_DELIVERY' ($facade + $service + $ledger) 'AddSupplies\(|ArrivalMs|GetDeliveryBaseTravelMs\('
Require 'AUTHORITY_RUNNING_GATE' $service '!Replication.IsServer\(\).*!m_Campaign.IsMaster\(\).*!m_Campaign.IsRunning\(\)'
Forbid 'NO_AUTOMATIC_LOGISTICS_SPAWN' (ConvertTo-AICFCodeText $service) '\.BeginLogisticsSpawn\s*\('
Forbid 'NO_AUTOMATIC_LOGISTICS_DELIVERY' (ConvertTo-AICFCodeText $service) 'm_Planner\.Select\s*\('
Require 'MANUAL_DISPATCH_RETAINS_JOB_SERVICE' (Method $service 'Update') 'UpdateJob\(worker, System.GetTickCount\(\), graphReady\)'
Require 'MANUAL_DISPATCH_RETAINS_CARGO_RETURN' (Method $service 'MaintainWorker') '(?s)if \(w.m_fObservedCargo > 0\).*?m_Planner.SelectReturn\(w\).*?BeginJobLeg\(w\)'
Require 'MANUAL_DISPATCH_RETAINS_VEHICLE_TICK' (Method $service 'Update') 'm_Vehicles.TickLogisticsWorker\(worker, m_Config, m_Book, graphReady\)'
Require 'GRAPH_PENDING_GATE' $service 'if \(!graphReady\) return;'
Require 'DEPOT_EXACT_ROOT' $registry 'BuildingRoot\(w.m_Production.GetOwner\(\)\) != w.m_Depot'
Require 'DEPOT_EXACT_PROVIDER' $registry 'composition.GetProviderEntity\(\) != w.m_Provider.GetOwner\(\)'
Require 'DEPOT_FINISHED' $registry '!composition.IsCompositionSpawned\(\)'
Require 'DEPOT_STABLE_ORDINAL' $registry 'w.m_iOrdinal == ordinal'
Require 'DEPOT_CATALOG_MEMBERSHIP' $registry 'm_aAssetList.Contains\(entry\)'
Require 'DEPOT_ALLOWED_SLOT' $registry 'data.CanSpawnInSlot\(slot.GetSlotType\(\)\)'
Require 'PREFERENCE_SKIPS_INCOMPATIBLE_ENTRY' $registry '!w.m_Production.AICF_LogisticsSupports\(entry\)'
Forbid 'DEPOT_QUERY_NONDESTRUCTIVE' ($registry + $acquisitionFlow) '\.IsOccupied\(|\.GetFreeSlot\('
Forbid 'LOGISTICS_UNCAPPED_ADMISSION' (Method (Read-Code 'State/Vehicles/AICF_FactionFleet.c') 'TryReserveLogistics') 'Get(?:Capped)?ActiveOrReservedCount|m_iMaximumActiveOrReserved'
Require 'INFANTRY_FLEET_CAP' (Method (Read-Code 'State/Vehicles/AICF_FactionFleet.c') 'CanReserveLease') 'GetCappedActiveOrReservedCount\(\) < m_iMaximumActiveOrReserved'
Require 'LOGISTICS_AI_BUDGET' (Method (Read-Code 'Vehicles/AICF_TransportTripController.c') 'BeginLogisticsSpawn') 'GetCurrentNumOfActiveAIs\(\) \+ m_aLogisticsSpawns.Count\(\) \+ 1 > world.GetLimitOfActiveAIs\(\)'
Require 'EMPTY_NEW_VEHICLE' $acquisition 'resources.EmptySpawnCargo\(w.m_Vehicle\)'
Require 'SINGLE_DRIVER' $acquisition 'HasExactFactionRoster\(w.m_Group, w.m_Faction.GetFactionKey\(\), 1,'
Require 'DRIVER_SPAWN_OUTSIDE_VEHICLE' $acquisitionFlow 'm_Drivers.CreateBuilder\(w.m_Faction, driverPosition\)'
Require 'DRIVER_SPAWN_CLEAR_GROUND' $acquisitionFlow 'SCR_WorldTools.FindEmptyTerrainPosition\(candidate, center, 1.5, 0.75, 2.0, TraceFlags.ENTS \| TraceFlags.OCEAN'
Require 'EXACT_PILOT' $worker 'm_Seat.GetOccupant\(\) != m_Driver'
Require 'DRIVER_READY_STILL_REJECTS_EXIT' $worker '!access.IsGettingOut\(\)'
Require 'GATE_TAG_EVIDENCE' $interaction 'tags.Contains\(SCR_AIGoalReaction_OpenNavlinkDoor.SMART_ACTION_TAG\)'
Require 'GATE_PRIORITY_EVIDENCE' $interaction 'perform.GetPriority\(\) != SCR_AIActionBase.PRIORITY_BEHAVIOR_OPEN_NAVLINK_DOOR'
Require 'GATE_SELECTED_CHAIN' $interaction 'current != perform && \(!exitAction \|\| current != exitAction\)'
Require 'GATE_EXACT_NATIVE_RETURN' $interaction 'getIn.m_CompartmentToGetIn.m_Value == w.m_Seat'
Require 'GATE_IMMUTABLE_JOB_TOKEN' $interaction 'm_Job.m_sToken != m_sToken'
Require 'GATE_IMMUTABLE_GENERATION' $interaction 'w.m_iGeneration != m_iGeneration'
Require 'GATE_LIVE_DRIVER_IDENTITY' $interaction 'w.VehicleIdentity\(\) && w.DriverIdentity\(\) && m_Utility'
Require 'GATE_STALL_DEADLINE' $interaction 'now - m_iProgressAtMs >= AICF_LogisticsConfig.DRIVER_INTERACTION_STALL_MS'
Require 'GATE_TOTAL_LEG_BUDGET' $interaction 'm_iWaitBeforeMs \+ elapsed >= AICF_LogisticsConfig.DRIVER_INTERACTION_LEG_BUDGET_MS'
Require 'GATE_EXACT_SETTLED_RETURN' $interaction 'opened && w.Ready\(\) && !Live\(m_Exit\)'
Require 'GATE_RENEW_BOUNDED' $ledger 'w.m_DriverInteraction.CanRenew\(w, System.GetTickCount\(\)\)'
Require 'GATE_TRANSFER_CLOSED' $ledger 'job.m_bCancelled \|\| w.m_DriverInteraction \|\| !w.Ready\(\)'
Require 'GATE_SERVICE_TRANSFER_CLOSED' $service 'if \(w.m_DriverInteraction\) return;'
Require 'GATE_RESERVATION_EXACT_OWNER' $worker 'seat == m_Seat && seat.IsReservedBy\(m_Driver\)'
Require 'GATE_PROGRESS_PAUSE_ACCOUNTING' $worker 'now - m_iProgressAtMs - \(m_iDriverWaitMs - m_iProgressWaitBaselineMs\)'
Require 'GATE_TERMINAL_BEFORE_JOB_CANCEL' $flows 'CancelLogisticsDriverInteraction\(w, reason\);\s*book.Cancel\(w\);'
Require 'GATE_TERMINAL_FOREIGN_SEAT_PROTECTED' $flows 'wait.m_Return.m_CompartmentToGetIn.m_Value = null;\s*wait.m_Return.Complete\(\);'
Forbid 'GATE_OBSERVER_NO_AI_MUTATION' $interaction '\.AddAction\(|\.GetInVehicle\(|\.GetOutVehicle\(|\.Complete\(|\.Fail\(|CallLater\(|\.Insert\('
Forbid 'RECOVERY_WAYPOINT_NOT_PROGRESS' $routeRecovery 'MarkProgress\('
Forbid 'RECOVERY_NO_RELOCATION' (ConvertTo-AICFCodeText ($routeRecovery + $driverRecovery)) 'SetOrigin\(|SetWorldTransform\(|GetInVehicle\(|GetOutVehicle\(|TELEPORT|CallLater\('
Require 'RECOVERY_EXACT_CONTEXT' $routeRecovery '!m_Context \|\| !m_Context.Matches\(w\)'
Require 'RECOVERY_BOUNDED_ATTEMPTS' $routeRecovery 'w.m_iRouteRetries >= AICF_LogisticsConfig.MAX_ROUTE_RETRIES'
Require 'RECOVERY_HARD_BUDGET' $routeRecovery 'RecoveryAge\(w, now\) >= AICF_LogisticsConfig.RECOVERY_BUDGET_MS'
Require 'RECOVERY_PHYSICAL_EVIDENCE' $routeRecovery 'vector.DistanceXZ\(position, m_vAttemptPosition\) >= 6'
Require 'RECOVERY_ROUTE_EVIDENCE' $routeRecovery 'vector.DistanceXZ\(position, m_vRoute\) \+ 3 <= m_fAttemptDistance'
Require 'RECOVERY_INTERMEDIATE_AFTER_EVIDENCE' $routeRecovery 'm_bIntermediate && !m_bSpawnEgress && !m_bActive && vector.DistanceXZ\(position, m_vRoute\) <= 8'
Require 'RECOVERY_QUERY_COMMIT_ON_SUCCESS' $routeRecovery '(?s)RoadEndpoint\(w, 0, initialRoad\)\).*?m_vRoute = initialRoad;'
Require 'RECOVERY_REACHABLE_ENDPOINT' $routeRecovery 'GetReachableWaypointInRoad\(origin, goal, 30, endpoint\)'
Require 'RECOVERY_TTL_BOUNDED' $ledger 'w.m_RouteRecovery.CanRenew\(w, now\)'
Require 'RECOVERY_TTL_NOT_RESURRECTED' $ledger 'now >= job.m_iExpiresAtMs'
Require 'UNKNOWN_EXIT_CLASSIFIED' $driverRecovery 'EXIT_CAUSE_UNRECOGNIZED'
Require 'UNKNOWN_EXIT_HARD_BUDGET' $driverRecovery 'now - m_iStartedAtMs >= AICF_LogisticsConfig.UNKNOWN_DRIVER_TIMEOUT_MS'
Require 'UNKNOWN_EXIT_TOTAL_BUDGET' $driverRecovery 'm_iWaitBeforeMs \+ now - m_iStartedAtMs >= AICF_LogisticsConfig.DRIVER_INTERACTION_LEG_BUDGET_MS'
Require 'UNKNOWN_EXIT_NATIVE_PRIORITY' $driverRecovery 'access.IsGettingIn\(\) \|\| access.IsGettingOut\(\) \|\| access.IsInCompartment\(\) \|\| NativeBusy\(true\)'
Require 'UNKNOWN_EXIT_FOREIGN_OCCUPANT' $driverRecovery 'if \(w.HasForeignOccupant\(true\)\) return AICF_TripOutcome.TerminalFailClosed'
Require 'UNKNOWN_EXIT_EXACT_RETURN' $driverRecovery 'if \(w.Ready\(\)\) return AICF_TripOutcome.CompleteTrip'
Require 'UNKNOWN_RETURN_SETTLING' $driverRecovery 'access.IsGettingIn\(\) \|\| \(m_Seat.GetOccupant\(\) == m_Driver && CompartmentAccessComponent.GetVehicleIn\(m_Driver\) == m_Vehicle\)'
Require 'UNKNOWN_RETURN_CALLBACK_TOKEN' $driverRecovery 'if \(token != m_sToken\) same = false;'
Require 'UNKNOWN_PAUSE_OWN_ROUTE' $driverRecovery 'w.m_Waypoint && !NativeBusy\(true\).*?Retry\("SUSPEND_UNKNOWN_EXIT_ROUTE"'
Require 'UNKNOWN_EXIT_NO_OTHER_SEAT' $driverRecovery '!access.GetCompartment\(\) \|\| access.GetCompartment\(\) == m_Seat'
Require 'DRIVER_SUCCESS_NOT_RETIREMENT' $flows 'observation.IsTerminal\(\) && observation.GetKind\(\) != AICF_ETripOutcomeKind.COMPLETE_TRIP'
Forbid 'UNKNOWN_RETURN_FAILURE_NO_STOCK_TELEPORT' (Method $driverRecovery 'OnActionFailed') 'super.OnActionFailed\('
Require 'EXIT_COOLDOWN_EXACT_IDENTITY' $exitHistory 'failure.m_Slot.GetOwner\(\).GetID\(\) != failure.m_SlotId'
Require 'EXIT_COOLDOWN_EXPIRES' $exitHistory 'now >= failure.m_iUntilMs'
Require 'EXIT_COOLDOWN_PROVEN_FAILURE' $exitHistory 'w.m_iRouteRetries >= AICF_LogisticsConfig.MAX_ROUTE_RETRIES'
Require 'EXIT_COOLDOWN_SKIP' $reserveSite 'w.m_ExitHistory.Cooling\(candidate, System.GetTickCount\(\)\)'
Require 'PLAYER_MAIN_ENTITY' $worker 'GetPlayerIdFromMainEntity\(m_Driver\)'
Require 'OWN_DRIVER_NOT_FOREIGN_OCCUPANT' $worker 'occupant && occupant != m_Driver'
Forbid 'NO_CLEANUP_OCCUPANT_GATE_FOR_MOVEMENT' ($flows + (Read-Code 'Vehicles/AICF_VehicleTransitFlow.c') + (Read-Code 'Vehicles/AICF_VehicleDismountFlow.c')) 'HasProtectedOccupant\(w.m_Vehicle\)'
Require 'DIRECTED_HQ_PATH' $planner 'FindFriendlyPath\(faction.GetMainBase\(\), base, faction.GetFactionKey\(\), path\)'
Require 'THRESHOLD_STRICT' $planner 'actual < capacity \* below / 100'
Require 'DONOR_STRICT' $planner 'actual <= capacity \* donate / 100'
Require 'NEUTRAL_SOURCE_ONLY' $planner 'SCR_CampaignSourceBaseComponent'
Require 'RESUMABLE_SEARCH' $planner 'search.m_aCandidates\[search.m_iCursor\+\+\]'
Require 'RESUMABLE_CANDIDATE_PREPARATION' $planner 'search.m_aEndpoints\[search.m_iSourceCursor\+\+\]'
Require 'PREPARATION_PENDING_NOT_FAILURE' $planner '!search.m_bPrepared && !PrepareCandidates\(w\)'
Require 'SEARCH_PENDING_NOT_FAILURE' $service 'if \(w.m_Search\) return;\s*w.m_iReturnAttempts\+\+'
Require 'SHARED_POOL_RESERVATIONS' $ledger 'job.m_Destination.m_Pool.Overlaps\(pool\)'
Require 'TTL_TOKEN_GENERATION' $ledger 'job.m_iGeneration != w.m_iGeneration'
Require 'RECEIPT_EXACTLY_ONCE' $ledger 'if \(receipt.m_bAccounted\) return false;'
Require 'PAIR_READBACK' $resource 'm_fBeforeFrom - receipt.m_fAfterFrom - receipt.m_fAmount'
Require 'COMPENSATE_EXACT_DEBIT' $resource 'float escrow = debited - credited;'
Require 'OPERATION_EXACT_POOL' $resource 'actual.Valid\(\) && expected.Same\(actual\)'
Require 'OPERATION_RESOURCE_RIGHTS' $resource '!operation.CanInteractWith\(container\)'
Require 'OPERATION_CONSUMING_STATE' $resource '!consumer.IsConsuming\(\)'
Forbid 'PHYSICAL_TRANSFER_NOT_TRADE_PRICE' $resource 'consumer.GetBuyMultiplier\('
Require 'PHYSICAL_STATIONARY_GATE' $service 'physics.GetVelocity\(\).Length\(\) > m_Config.m_fStationarySpeedMps'
Require 'RETURN_SOURCE_PROVENANCE' $service 'job.m_OriginalSource.m_Pool == destination.m_Pool'
Require 'BATCH_UNKNOWN_EXTERNAL' $ledger 'original_source=UNKNOWN'
Require 'REAL_LOSS_ONLY' $ledger 'delta < 0 && damage && damage.IsDestroyed\(\)'
Require 'STOCK_FIRE_LOSS_ACCOUNTED' $ledger 'reason=STOCK_SUPPLIES_FIRE'
Require 'STOCK_FIRE_OBSERVATION' (Read-Code 'Economy/AICF_LogisticsDamageAccounting.c') 'super.UpdateSuppliesFireState\(fireRate, timeSlice\);'
Require 'STOCK_FIRE_CUSTODY_UNBOUND' $ledger 'damage.AICF_SetLogisticsCustody\(null\)'
Require 'SURVIVING_CARGO_RELEASE' $cleanup 'CanDeleteVehicle\(vehicle\).*ReleaseToWorldPool'
Require 'GLOBAL_CARGO_DELETE_GUARD' $delete 'if \(!AICF_LogisticsResourceAdapter.CanDeleteVehicle\(vehicle\)\)\s*return false;\s*RplComponent.DeleteRplEntity\(vehicle, false\);'
Require 'REMOVE_WAYPOINT_BEFORE_DELETE' $flows '(?s)RemoveWaypoint\(waypoint\).*?DeleteRplEntity\(waypoint, false\)'
Require 'EXTENDED_CONSERVATION' $worker 'm_fLoaded \+ m_fExternalIn - m_fDelivered - m_fReturned - cargo - m_fLost - m_fReleased - m_fExternalOut'
foreach ($callback in @('OwnerChanged','Placed','Removed')) {
    Require "EVENT_INSERT_$callback" $registry "\.Insert\($callback\)"
    Require "EVENT_REMOVE_$callback" $registry "\.Remove\($callback\)"
}
Require 'COMPOSITION_EVENT_CLEANUP' $registry 'GetOnCompositionSpawned\(\).Remove\(Changed\)'
Forbid 'FLOW_PHASE_OWNERSHIP' $acquisitionFlow 'm_ePhase\s*=\s*[^=]|LogisticsPhase\(|QueueLogisticsRelease\('
Forbid 'LOGISTICS_NO_INFANTRY_ASSIGNMENTS' ($service + $planner) 'SetAssignment|SetTarget|SetRole|RequestGroupConfiguration'
if ($failures.Count) { $failures | ForEach-Object { "FAIL $_" }; exit 1 }


Forbid 'SPAWN_ALL_PHYSICAL_OBSTACLES' ($bodyClear + $spawnClear + $slotClear + $spawnGeometry) 'ExcludeArray|\.Exclude\s*=|KeepExternalObstacle|AICF_LogisticsExclusions'
Forbid 'SPAWN_SEARCH_READ_ONLY' $spawnGeometry 'Delete|delete |SetOrigin|SetTransform|SpawnEntity|IsOccupied\('
Require 'SPAWN_SEARCH_BOUNDED' $reserveSlot 'candidate < AICF_LogisticsSpawnGeometry.CANDIDATES'
Require 'SPAWN_OFFSET_BOUNDED' $spawnClear 'vector.DistanceXZ\(position, w.m_aSlotTransform\[3\]\) > AICF_LogisticsSpawnGeometry.MAX_OFFSET_M'
Require 'SPAWN_EXIT_SWEEP' $spawnGeometry 'if \(world.TraceMove\(trace, null\) < 1\) return false;'
Require 'SPAWN_EXIT_GROUND' $spawnGeometry 'if \(!FitToSurface\(world, footprint, next\)\) return false;'
Require 'SPAWN_GROUND_WATER' $spawnGeometry 'if \(ChimeraWorldUtils.TryGetWaterSurfaceSimple\(world, waterPoint\)\) return false;'
Require 'SPAWN_GROUND_SUPPORT' $spawnGeometry 'highest - lowest > 0.6'
Require 'SPAWN_FIRST_LEG_EXIT' $routeRecovery '(?s)!w.m_bSpawnExitReached.*?m_vRoute = w.m_vSpawnExit;.*?m_bSpawnEgress = true;'
Require 'SPAWN_EXIT_PHYSICAL_PROGRESS' $routeRecovery 'm_bSpawnEgress && !m_bActive && vector.DistanceXZ\(position, m_vRoute\) <= 5'
if ($failures.Count) { $failures | ForEach-Object { "FAIL $_" }; exit 1 }

'PASS Logistics static contracts (не заменяет Enforce compile/runtime)'
