param([string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Stage3StaticAudit.Common.ps1')
$records = @(Get-AICFSourceRecords $RepositoryRoot)
$rpc = $records | Where-Object Name -eq 'AICF_SupplyTransportRpc.c'
$dispatch = Find-AICFClassRecord $records 'AICF_ManualSupplyDispatch'
$planner = Find-AICFClassRecord $records 'AICF_LogisticsPlanner'
$service = Find-AICFClassRecord $records 'AICF_LogisticsService'
$view = Find-AICFClassRecord $records 'AICF_SupplyMapUI'
$data = Find-AICFClassRecord $records 'AICF_SupplyMapBase'
$match = Find-AICFClassRecord $records 'AICF_MatchController'
$registry = Find-AICFClassRecord $records 'AICF_LogisticsDepotRegistry'
$fleet = Find-AICFClassRecord $records 'AICF_FactionFleet'
$config = Find-AICFClassRecord $records 'AICF_LogisticsConfig'
$trip = Find-AICFClassRecord $records 'AICF_TransportTripController'
$probe = @(Get-AICFSourceRecords $RepositoryRoot @('tools/fixtures')) | Where-Object Name -eq 'AICF_ManualSupplyClientProbe.c'
$failures = [Collections.Generic.List[string]]::new()
$negativeCount = 0
function Method($Record, [string]$Name) {
    if (-not $Record) { throw "Missing record for $Name" }
    (ConvertTo-AICFCodeText (Get-AICFMethodBody $Record $Name)) -replace '\s+', ' '
}
function Require([string]$Rule, [string]$Code, [string]$Pattern, [string]$Mutation = '') {
    Assert-AICFContains $failures $Rule $Code $Pattern 'Manual supply transport contract'
    if ($Mutation) {
        if (-not $Code.Contains($Mutation)) { throw "Mutation absent: $Rule" }
        $broken = $Code.Replace($Mutation, '/* removed by negative case */')
        if ($broken -match $Pattern) { $failures.Add("[$Rule] Negative input was not rejected") }
        $script:negativeCount++
    }
}
$submit = Method $dispatch 'Submit'
$update = Method $dispatch 'Update'
$finish = Method $dispatch 'Finish'
$endpoint = Method $dispatch 'EndpointsValid'
$ask = Method $rpc 'RpcAsk_AICFSupplyTransport'
$request = Method $rpc 'AICF_RequestSupplyTransport'
$pending = Method $rpc 'AICF_IsSupplyRequestPending'
$amount = Method $view 'RefreshAmount'
Require 'MANUAL_AUTHORITY' $submit '!Replication.IsServer\(\)' '!Replication.IsServer()'
Require 'MANUAL_CONTROLLER_OWNER' $submit 'GetPlayerController\(playerId\) != player' 'GetPlayerController(playerId) != player'
Require 'MANUAL_FACTION_AUTHORITY' $submit 'SGetPlayerFaction\(playerId\)' 'SGetPlayerFaction(playerId)'
Require 'MANUAL_SUPPORTED_SIDE' (Method $match 'RequestSupplyTransport') 'faction != m_USFaction && faction != m_USSRFaction'
Require 'MANUAL_MATCH_READINESS' (Method $match 'RequestSupplyTransport') '!m_bRosterReady[\s\S]*m_bReplanScheduled \|\| m_bGraphRebuildNeeded'
Require 'MANUAL_RPC_DEDUP' $ask 'request <= m_iAICFSupplyRequest\) return' 'request <= m_iAICFSupplyRequest'
Require 'MANUAL_PENDING_REPLY' $pending 'return m_iAICFSupplySent > m_iAICFSupplyRequest;' 'm_iAICFSupplySent > m_iAICFSupplyRequest'
Require 'MANUAL_CLIENT_PENDING_ONLY' $request 'AICF_IsSupplyRequestPending\(\)\) return;[\s\S]*m_iAICFSupplySent = m_iAICFSupplyRequest \+ 1' 'AICF_IsSupplyRequestPending()'
Assert-AICFNotContains $failures 'MANUAL_NO_ACTIVE_REQUEST_GATE' ($ask + $request + $pending) 'm_bAICFSupplyBusy|AICF_IsSupplyBusy\(' 'Active trips must not block a new request'
Require 'MANUAL_RPC_RATE' $ask 'now < m_iAICFSupplyRateAtMs[\s\S]*m_iAICFSupplyRateAtMs = now \+ 2000'
Require 'MANUAL_RPC_RELIABLE' $rpc.Code '\[RplRpc\(RplChannel.Reliable, RplRcver.Server\)\]'
Require 'MANUAL_NETWORK_ID' (Method $dispatch 'ResolveBase') 'Replication.FindItem\(id\)' 'Replication.FindItem(id)'
Require 'MANUAL_NETWORK_ID_CLIENT' (Method $data 'NetworkId') 'm_EntityId[\s\S]*rpl.Id\(\)'
Assert-AICFNotContains $failures 'MANUAL_INTENT_ONLY' $rpc.Code 'RpcAsk_AICFSupplyTransport\([^)]*(?:Faction|playerId|EntityID)' 'RPC accepts intent, never authoritative identity'
Require 'MANUAL_BOTH_ENDPOINTS' $endpoint 'OwnedSafe\(source, faction\)[\s\S]*OwnedSafe\(destination, faction\)' 'OwnedSafe(destination, faction)'
Require 'MANUAL_NO_SELF_TRANSFER' $endpoint 'source.m_Pool.Overlaps\(destination.m_Pool\)' 'source.m_Pool.Overlaps(destination.m_Pool)'
Require 'MANUAL_AMOUNT_BOUNDS' $endpoint 'amount <= 0 \|\| amount > available' 'amount <= 0'
Require 'MANUAL_DESTINATION_CAPACITY' $endpoint 'amount > free' 'amount > free'
Require 'MANUAL_PRESERVE_COMMITMENTS' (Method $planner 'ManualAvailable') 'LogisticsObligations\(e.m_Base\)[\s\S]*Reserved\(e.m_Pool, false, exclude\)' 'LogisticsObligations(e.m_Base)'
Require 'MANUAL_REQUEST_DEDUP' $submit 'previous.m_Player == player && previous.m_iRequest == token' ' && previous.m_iRequest == token'
Require 'MANUAL_ADMISSION_RATE' $submit 'now < m_iNextAdmissionMs[\s\S]*m_iNextAdmissionMs = now \+ 500'
Assert-AICFNotContains $failures 'MANUAL_NO_REQUEST_COUNT_CAP' $submit 'm_aRequests.Count\(\)\s*(?:[<>]=?|==|!=)' 'Request count has no separate cap; worker/fleet/AI admission remains authoritative'
Require 'MANUAL_FREE_EXACT_WORKER' $submit 'OwnsWorker\(w\)[\s\S]*w.m_Group \|\| w.m_Vehicle \|\| w.m_bCustody'
Require 'MANUAL_STABLE_WORKER' $submit 'w.m_iSlot >= selected.m_iSlot'
Require 'MANUAL_REPLACEMENT_COOLDOWN' $submit 'm_bCleanupComplete && now < w.m_iRetryAtMs \+ m_Planner.m_Config.m_iReplacementCooldownMs'
Require 'MANUAL_ROUTE_BEFORE_SPAWN' $submit 'Route\(load, destination, unload\)[\s\S]*BeginLogisticsSpawn\(selected\)[\s\S]*m_iGeneration = selected.m_iGeneration'
Require 'MANUAL_DYNAMIC_WORKER' $submit 'if \(addWorker\) selected = expansionDepot;[\s\S]*Route\(load, destination, unload\)[\s\S]*if \(addWorker\) \{ selected = m_Registry.AddManualWorker\(selected\);' 'selected = m_Registry.AddManualWorker(selected);'
Require 'MANUAL_REUSE_BEFORE_EXPANSION' $submit 'bool addWorker = !selected;' 'bool addWorker = !selected;'
Require 'MANUAL_NEW_CAPACITY' $submit 'amount <= newCapacity &&[\s\S]*expansionDepot = w;' 'amount <= newCapacity &&'
Require 'MANUAL_WORKER_AUTHORITY' (Method $registry 'AddManualWorker') 'm_bStopped \|\| !Replication.IsServer\(\) \|\| !depot \|\| !m_aWorkers.Contains\(depot\)' '!m_aWorkers.Contains(depot)'
Require 'MANUAL_WORKER_LIVE' (Method $registry 'AddManualWorker') 'depot.m_bStopped \|\| !Live\(depot\)\) return null;' '!Live(depot)'
Require 'MANUAL_WORKER_NEW_ORDINAL' (Method $registry 'AddManualWorker') 'ordinal = Math.Max\(ordinal, sibling.m_iOrdinal \+ 1\)' 'sibling.m_iOrdinal + 1'
Require 'MANUAL_WORKER_STABLE_SLOT' (Method $registry 'CreateWorker') 'w.m_iSlot = m_iNextSlot\+\+;' 'm_iNextSlot++'
Require 'MANUAL_DEPOT_SEED_ONLY' (Method $registry 'Inspect') 'if \(!Find\(root, faction, 0\)\) CreateWorker\(root, faction, home, production, 0\);' '!Find(root, faction, 0)'
Assert-AICFNotContains $failures 'MANUAL_NO_DEPOT_COUNT_CAP' ($registry.Code + $config.Code) 'm_iWorkersPerDepot|ReadInt\("WorkersPerDepot"' 'Depot workers grow per request without a numeric cap'
Assert-AICFNotContains $failures 'MANUAL_NO_FLEET_COUNT_CAP' (Method $fleet 'TryReserveLogistics') 'Get(?:Capped)?ActiveOrReservedCount|m_iMaximumActiveOrReserved' 'Logistics admission is independent of fleet vehicle cap'
Require 'MANUAL_KEEP_AI_BUDGET' (Method $trip 'BeginLogisticsSpawn') 'GetCurrentNumOfActiveAIs\(\) \+ m_aLogisticsSpawns.Count\(\) \+ 1 > world.GetLimitOfActiveAIs\(\)' ' + m_aLogisticsSpawns.Count()'
Require 'MANUAL_KEEP_LEASE_IDENTITY' (Method $fleet 'TryReserveLogistics') 'w.m_Faction.GetFactionKey\(\) != m_sFactionKey \|\| HasLeaseForSlot\(w.m_iSlot\)' 'HasLeaseForSlot(w.m_iSlot)'
Require 'MANUAL_INFANTRY_CAP_EXCLUDES_LOGISTICS' (Method $fleet 'GetCappedActiveOrReservedCount') 'lease.IsCapActive\(\) && lease.GetSlotId\(\) < AICF_LogisticsConfig.SERVICE_SLOT_FIRST' 'lease.GetSlotId() < AICF_LogisticsConfig.SERVICE_SLOT_FIRST'
Require 'MANUAL_ASYNC_GENERATION' $update 'w.m_iGeneration != request.m_iGeneration' 'w.m_iGeneration != request.m_iGeneration'
Require 'MANUAL_PLAYER_RECHECK' (Method $dispatch 'PlayerValid') 'GetPlayerController\(request.m_iPlayer\) == request.m_Player[\s\S]*SGetPlayerFaction\(request.m_iPlayer\) == request.m_Worker.m_Faction'
Require 'MANUAL_READY_BEFORE_RESERVE' $update '!w.Ready\(\)[\s\S]*EndpointsValid\([\s\S]*m_CargoPool.Capacity\(\)[\s\S]*m_Book.Reserve\(' '!w.Ready()'
Require 'MANUAL_ACQUISITION_BEFORE_RESERVE' $update 'w.m_ePhase == AICF_ELogisticsPhase.SPAWN_PENDING \|\| !w.Ready\(\)\) continue;[\s\S]*m_Book.Reserve\(' 'w.m_ePhase == AICF_ELogisticsPhase.SPAWN_PENDING || '
Require 'MANUAL_EXACT_ENDPOINT_JOB' $update 'Reserve\(w, request.m_Source, request.m_Destination, request.m_iAmount'
Require 'MANUAL_JOB_BEFORE_MOVEMENT' $update 'request.m_Job = w.m_Job; request.m_Job.m_bManual = true;[\s\S]*BeginLogisticsLeg'
Require 'MANUAL_CANCEL_IDENTITY' $finish 'w.m_iGeneration == request.m_iGeneration[\s\S]*w.m_Job == request.m_Job[\s\S]*m_Book.Cancel\(w\)' 'w.m_Job == request.m_Job'
Require 'MANUAL_RESULT_ACTUAL_DELIVERY' $update 'w.m_fDelivered - request.m_fDeliveredBefore' 'w.m_fDelivered - request.m_fDeliveredBefore'
Require 'MANUAL_STATUS_OWNER_SNAPSHOT' $rpc.Code 'RplProp\(condition: RplCondition.OwnerOnly\)[\s\S]*m_sAICFSupplyStatus'
Require 'MANUAL_STATUS_AUTHORITY_CHANGE_ONLY' (Method $rpc 'AICF_SetSupplyStatus') '!Replication.IsServer\(\)[\s\S]*status == m_sAICFSupplyStatus\) return[\s\S]*Replication.BumpMe\(\)'
Require 'MANUAL_STATUS_LATEST_REQUEST' (Method $rpc 'AICF_SetSupplyStatus') 'request < m_iAICFSupplyRequest\) return;[\s\S]*m_iAICFSupplyRequest = request;' 'request < m_iAICFSupplyRequest'
Require 'MANUAL_NO_IDLE_INTERFERENCE' (Method $service 'MaintainWorker') 'm_Manual.OwnsWorker\(w\)\) return' 'm_Manual.OwnsWorker(w)'
Require 'MANUAL_STOP' (Method $service 'Stop') 'm_Manual.Stop\(\)[\s\S]*m_Registry.Stop\(\)'
Require 'MANUAL_DESTINATION_EXPLICIT' (Method $view 'RebuildDestinations') 'm_Destination = null;[\s\S]*selectedIndex = m_aDestinations.Count\(\)'
Require 'MANUAL_SEND_RECHECK' (Method $view 'Send') 'Refresh\(\); if \(!m_bOpen \|\| !m_bCanSend\) return;[\s\S]*AICF_RequestSupplyTransport\(m_Selected.NetworkId\(\), m_Destination.NetworkId\(\), m_iAmount\)'
Require 'MANUAL_UI_CONCURRENT_SEND' $amount 'bool pending = player && player.AICF_IsSupplyRequestPending\(\); m_bCanSend = player && !pending && ready' 'AICF_IsSupplyRequestPending()'
Require 'MANUAL_UI_CONCURRENT_EDIT' $amount 'm_Combo.SetEnabled\(!pending && !m_aBases.IsEmpty\(\)\); m_DestinationCombo.SetEnabled\(!pending && !m_aDestinations.IsEmpty\(\)\); if \(pending\) \{ m_Slider.SetEnabled\(false\); \}' '!pending && !m_aDestinations.IsEmpty()'
Assert-AICFNotContains $failures 'MANUAL_UI_NO_ACTIVE_GATE' $amount 'm_bCanSend = [^;]*!busy|SetEnabled\([^;]*!busy|if \(busy\) \{ m_Slider.SetEnabled\(false\)' 'Latest trip status must not disable form input'
Require 'MANUAL_UI_VALIDATION_VISIBLE' $amount 'm_wStatus.SetVisible\(true\); PlaceControl\(m_wResult, 0.05, 0.77, 0.95, 0.89\);' 'm_wStatus.SetVisible(true);'
Assert-AICFNotContains $failures 'MANUAL_UI_NO_VALIDATION_OVERLAP' $amount 'AICF_IsSupplyBusy\(|PlaceControl\(m_wResult, 0.05, 0.70' 'Validation and latest-trip result keep separate visible regions'
Require 'MANUAL_PROBE_ALL_RESULTS' (Method $probe 'CanClose') 'submissionsDone && !pending && accepted >= 0 && finished == accepted' 'finished == accepted'
Require 'MANUAL_PROBE_ACCEPTED_DEDUP' (Method $probe 'Observe') 'm_aAccepted.Contains\(request\)\) return false; m_aAccepted.Insert\(request\)' 'm_aAccepted.Contains(request)'
Require 'MANUAL_PROBE_TERMINAL_IDENTITY' (Method $probe 'Observe') '!m_aAccepted.Contains\(request\) \|\| m_aFinished.Contains\(request\)\) return false; m_aFinished.Insert\(request\)' 'm_aFinished.Contains(request)'
Require 'MANUAL_PROBE_OWNER_SNAPSHOT' $probe.Code 'RplProp\(condition: RplCondition.OwnerOnly\)\]\s+protected int m_iAICFManualProbeAcceptedCount'
Require 'MANUAL_PROBE_FINISHED_SNAPSHOT' $probe.Code 'RplProp\(condition: RplCondition.OwnerOnly\)\]\s+protected int m_iAICFManualProbeFinishedCount'
Require 'MANUAL_PROBE_OBSERVES_OLD_RESULTS' (Method $probe 'AICF_SetSupplyStatus') 'super.AICF_SetSupplyStatus\(request, busy, status\); if \(!Replication.IsServer\(\) \|\| !m_AICFManualProbeResults.Observe\(request, busy\)\) return;[\s\S]*Replication.BumpMe\(\)'
Require 'MANUAL_PROBE_CLOSE_GUARD' (Method $probe 'AICF_ManualProbeClose') '!player.AICF_ManualProbeCanClose\(m_bAICFManualProbeSecondSent \|\| m_bAICFManualProbeTimedOut\)\)\) return;[\s\S]*RequestClose\(\)' '!player.AICF_ManualProbeCanClose(m_bAICFManualProbeSecondSent || m_bAICFManualProbeTimedOut)'
Require 'MANUAL_PROBE_SINGLE_ONLY_EARLY_EXIT' (Method $probe 'AICF_ManualProbeTick') 'if \(!m_bAICFManualProbeConcurrent && m_bAICFManualProbeAccepted && !player.AICF_IsSupplyBusy\(\)\)' '!m_bAICFManualProbeConcurrent && m_bAICFManualProbeAccepted'
Require 'MANUAL_PROBE_TIMEOUT_WAIT' (Method $probe 'AICF_ManualProbeDeadline') 'if \(!m_bAICFManualProbeConcurrent\) \{ AICF_ManualProbeClose\(\); return; \} m_bAICFManualProbeTimedOut = true;[\s\S]*AICF_ManualProbeTick\(\)'
Require 'MANUAL_PROBE_DEADLINE_CLEANUP' (Method $probe 'AICF_ManualProbeClose') 'Remove\(AICF_ManualProbeDeadline\)' 'Remove(AICF_ManualProbeDeadline)'
Require 'MANUAL_DESTINATION_LIFETIME' (Method $view 'Detach') 'm_DestinationCombo.m_OnChanged.Remove\(OnDestinationChanged\)' 'm_DestinationCombo.m_OnChanged.Remove(OnDestinationChanged)'
Assert-AICFNotContains $failures 'MANUAL_NO_RESOURCE_SIDE_EFFECT' ($view.Code + $rpc.Code + $dispatch.Code) 'AddSupplies\(|SpawnEntity|DeleteRplEntity|\.Transfer\(|SetResourceValue\(' 'Only existing owners perform physical/economic side effects'
if ($failures.Count) { $failures; exit 1 }
Write-Output "PASS Manual supply: authority, RPC/replicated result, bounds, exact route, generation, lifecycle; $negativeCount negative inputs. Runtime is a separate gate."
exit 0
