param([string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'Stage3StaticAudit.Common.ps1')
$records = @(Get-AICFSourceRecords $RepositoryRoot)
$failures = [Collections.Generic.List[string]]::new()
$negativeCount = 0
function Method([string]$File, [string]$Name) {
    $record = $records | Where-Object Name -eq $File
    if (@($record).Count -ne 1) { throw "Ожидался один production source: $File" }
    (ConvertTo-AICFCodeText (Get-AICFMethodBody $record $Name)) -replace '\s+', ' '
}
function Require([string]$Rule, [string]$Code, [string]$Pattern, [string]$Remove = '') {
    Assert-AICFContains $failures $Rule $Code $Pattern 'AI loadout contract'
    if ($Remove) {
        if (-not $Code.Contains($Remove)) { throw "Нет отрицательной мутации $Rule" }
        if ($Code.Replace($Remove, '') -match $Pattern) { $failures.Add("[$Rule] Отрицательная копия не отклонена") }
        $script:negativeCount++
    }
}
$context = Method 'AICF_MatchController.c' 'ResolveLoadoutContext'
Require 'LOADOUT_AUTHORITY' $context '!Replication.IsServer\(\)' '!Replication.IsServer()'
Require 'LOADOUT_PLAYER_OWNER' $context 'GetPlayerController\(player.GetPlayerId\(\)\) != player' 'GetPlayerController(player.GetPlayerId()) != player'
Require 'LOADOUT_FACTION' $context 'SGetPlayerFaction\(player.GetPlayerId\(\)\)' 'SGetPlayerFaction(player.GetPlayerId())'
Require 'LOADOUT_MATCH_GATE' $context '!m_bRosterReady.*!m_Campaign.IsMaster\(\).*!m_Campaign.IsRunning\(\)' '!m_Campaign.IsMaster()'
Require 'LOADOUT_MEMBER_BOUND' $context 'member >= slot.GetDesiredSize\(\)' 'member >= slot.GetDesiredSize()'
$request = Method 'AICF_LoadoutService.c' 'Request'
Require 'LOADOUT_CONTENT_BOUNDARY' $request 'candidate.m_sProfile == recipe.m_sProfile.*candidate.m_sFaction == recipe.m_sFaction.*candidate.m_sCharacter == source' 'candidate.m_sCharacter == source'
Require 'LOADOUT_REVISION' $request 'revision != slot.GetLoadoutRevision\(\)' 'revision != slot.GetLoadoutRevision()'
Require 'LOADOUT_SAVE_BEFORE_BIND' $request 'm_Store.Save\(candidate, reason\).*slot.SetLoadout\(member, binding, revision\)' 'm_Store.Save(candidate, reason)'
$rpc = Method 'AICF_LoadoutRpc.c' 'RpcAsk_AICFLoadout'
Require 'LOADOUT_TOKEN' $rpc 'token <= m_iAICFLoadoutToken' 'token <= m_iAICFLoadoutToken'
Require 'LOADOUT_PAYLOAD_BOUND' $rpc 'payload.Length\(\) > AICF_LoadoutRecipe.MAX_BYTES' 'payload.Length() > AICF_LoadoutRecipe.MAX_BYTES'
Require 'LOADOUT_RATE_LIMIT' $rpc 'now < m_iAICFLoadoutRateAt.*m_iAICFLoadoutRateAt = now \+ 750' 'now < m_iAICFLoadoutRateAt'
$bounds = Method 'AICF_LoadoutRecipe.c' 'HasValidBounds'
Require 'LOADOUT_ARRAY_BOUNDS' $bounds 'count > MAX_OPERATIONS.*m_aCounts.Count\(\) != count.*m_aPrefabs.Count\(\) != count' 'm_aCounts.Count() != count'
Require 'LOADOUT_QUANTITY_BOUNDS' $bounds 'm_aCounts\[i\] < 1 \|\| m_aCounts\[i\] > 16' 'm_aCounts[i] > 16'
Require 'LOADOUT_DEPTH_BOUND' $bounds 'segments.Count\(\) > 6' 'segments.Count() > 6'
$replay = Method 'AICF_LoadoutInventory.c' 'Replay'
Require 'LOADOUT_VALIDATE_BEFORE_MUTATE' $replay 'catalog.Allows\(candidate\).*DeleteLocal\(storage.Get\(slot\)\)' 'catalog.Allows(candidate)'
Require 'LOADOUT_CAPACITY' $replay 'manager.CanInsertResourceInStorage\(prefab, storage, slot\)' 'manager.CanInsertResourceInStorage(prefab, storage, slot)'
Require 'LOADOUT_LOCAL_DELETE_ONLY' (Method 'AICF_LoadoutInventory.c' 'DeleteLocal') 'item.GetWorld\(\) == GetGame\(\).GetWorld\(\)' 'item.GetWorld() == GetGame().GetWorld()'
Require 'LOADOUT_DETACH_BEFORE_DELETE' (Method 'AICF_LoadoutInventory.c' 'DeleteLocal') 'parent.GetAttachedEntity\(\) != item.*parent.DetachEntity\(\).*component.GetParentSlot\(\).*DeleteEntityAndChildren\(item\)' 'parent.DetachEntity()'
Require 'LOADOUT_LOCAL_INSERT_ONLY' (Method 'AICF_LoadoutInventory.c' 'InsertLocal') 'storage.GetOwner\(\).GetWorld\(\) == GetGame\(\).GetWorld\(\)' 'storage.GetOwner().GetWorld() == GetGame().GetWorld()'
$restore = Method 'AICF_LoadoutInventory.c' 'Restore'
Require 'LOADOUT_SERVER_RESTORE' $restore '!Replication.IsServer\(\).*controller.IsPlayerControlled\(\).*!rpl.IsMaster\(\)\) return false;.*ApplyEntityStorageString' '!rpl.IsMaster()'
$apply = Method 'AICF_LoadoutApplicator.c' 'Apply'
Require 'LOADOUT_APPLY_IDENTITY' $apply 'character.GetID\(\) != identity.*control.GetControlAIAgent\(\).GetParentGroup\(\) != group' 'character.GetID() != identity'
Require 'LOADOUT_APPLY_READBACK' $apply 'Restore\(character, binding.m_sInventory\).*Signature\(character, catalog, ignored\) != binding.m_sSignature' 'Signature(character, catalog, ignored) != binding.m_sSignature'
$validate = Method 'AICF_LoadoutService.c' 'Validate'
Require 'LOADOUT_AMMO' $validate 'HasUsableWeapons\(draft.GetCharacter\(\), reason\)' 'HasUsableWeapons(draft.GetCharacter(), reason)'
Require 'LOADOUT_FREE_TEMPLATE' $validate 'binding.m_iCost = 0;' 'binding.m_iCost = 0;'
Assert-AICFNotContains $failures 'LOADOUT_NO_PRICE_CAP' $validate 'binding.m_iCost >|GetBaselineCost\(' 'Цена арсенала не ограничивает бесплатный комплект бота'
Require 'LOADOUT_FREE_DEPLOYMENT' (Method 'AICF_GroupSlot.c' 'GetDeploymentLoadoutCost') 'return 0;' 'return 0;'
Require 'LOADOUT_SAVE_READBACK' (Method 'AICF_LoadoutStore.c' 'Save') 'FileIO.FileExists\(Path\(i\)\).*continue;.*SaveToFile\(Path\(i\)\).*LoadFromFile\(Path\(i\)\).*saved.Encode\(\) != recipe.Encode\(\)' 'saved.Encode() != recipe.Encode()'
Require 'LOADOUT_PREVIEW_ISOLATED' (Method 'AICF_LoadoutInventory.c' 'Build') 'BaseWorld.CreateWorld.*m_Character.GetWorld\(\) == GetGame\(\).GetWorld\(\)'
Require 'LOADOUT_PREVIEW_CLEANUP' (Method 'AICF_LoadoutInventory.c' 'Clear') 'delete m_Preview.*DeleteEntityAndChildren\(m_Character\).*m_World = null'
Require 'LOADOUT_ROTATION_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'Remove\(RotatePreview\).*RemoveActionListener.*m_OnChanged.Remove\(OnChanged\).*m_Draft.Clear\(\)'
Require 'LOADOUT_PRIVATE_CAMERA' (Method 'AICF_LoadoutPreview.c' 'Build') 'BaseWorld.CreateWorld.*CreatePreviewEntity\(m_World, 0\)' 'CreatePreviewEntity(m_World, 0)'
Require 'LOADOUT_PREVIEW_WORLD_BIND' (Method 'AICF_LoadoutEditor.c' 'Rebuild') 'm_wPreview.SetWorld\(m_Preview.GetWorld\(\), 0\)' 'm_wPreview.SetWorld(m_Preview.GetWorld(), 0)'
Require 'LOADOUT_PREVIEW_BUDGET' (Method 'AICF_LoadoutEditor.c' 'Create') 'm_wPreview.SetMaxFPS\(30\)' 'm_wPreview.SetMaxFPS(30)'
Require 'LOADOUT_MODAL_INPUT_LAYER' (Method 'AICF_LoadoutEditor.c' 'Create') 'm_wPanel.SetZOrder\(5\)' 'm_wPanel.SetZOrder(5)'
Require 'LOADOUT_PALETTE_REFRESH' (Method 'AICF_LoadoutEditor.c' 'Refresh') 'RefreshColors\(\)' 'RefreshColors()'
Require 'LOADOUT_GROUP_OWN_FACTION' (Method 'AICF_StrategicUI.c' 'GetLoadoutGroup') 'slotId >= AICF_Stage1Config.GROUP_SLOTS_PER_FACTION.*AICF_GetStrategicGroupSummary\(m_bLocalUSSR, slotId\)' 'AICF_GetStrategicGroupSummary(m_bLocalUSSR, slotId)'
Require 'LOADOUT_GROUP_STABLE_ID' (Method 'AICF_LoadoutEditor.c' 'OnChanged') 'component == m_Group && !m_bPending.*SelectTarget\(m_aGroupIds\[index\], 0\)' 'm_aGroupIds[index]'
Require 'LOADOUT_TARGET_SWITCH' (Method 'AICF_LoadoutEditor.c' 'SelectTarget') 'm_bPending.*RememberDraft\(\).*m_iSlotId = slotId.*m_iRevision = -1.*m_Recipe = null.*m_bDraftReady = false.*Request\(0\)' 'm_bDraftReady = false'
Require 'LOADOUT_TARGET_MEMBER_COUNT' (Method 'AICF_LoadoutEditor.c' 'PopulateMembers') 'GetLoadoutGroup\(m_iSlotId, name, size\).*ClearAll\(\).*Math.Min\(size, roles.Count\(\)\)' 'GetLoadoutGroup(m_iSlotId, name, size)'
Require 'LOADOUT_DRAFT_SCOPE' (Method 'AICF_LoadoutEditor.c' 'Key') 'slot >= AICF_Stage1Config.GROUP_SLOTS_PER_FACTION.*member >= AICF_Stage1Config.MAX_GROUP_SIZE.*slot \* AICF_Stage1Config.MAX_GROUP_SIZE \+ member' 'slot * AICF_Stage1Config.MAX_GROUP_SIZE + member'
Require 'LOADOUT_DRAFT_REVISION' (Method 'AICF_LoadoutEditor.c' 'Recover') 'savedRevision != revision.*stale = true.*Forget\(slot, member\)' 'savedRevision != revision'
Require 'LOADOUT_DRAFT_SOURCE' (Method 'AICF_LoadoutEditor.c' 'Refresh') 'draft.m_sProfile == m_Recipe.m_sProfile.*draft.m_sFaction == m_Recipe.m_sFaction.*draft.m_sCharacter == m_Recipe.m_sCharacter' 'draft.m_sCharacter == m_Recipe.m_sCharacter'
Require 'LOADOUT_DRAFT_VS_APPLIED' (Method 'AICF_LoadoutEditor.c' 'RememberDraft') 'data != m_sAppliedData.*m_DraftMemory.Remember\(m_iSlotId, m_iMember, m_iRevision, data\)' 'data != m_sAppliedData'
Require 'LOADOUT_DRAFT_MEMORY_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_aGroupIds.Clear\(\).*m_aGroupNames.Clear\(\).*m_DraftMemory.Clear\(\)' 'm_DraftMemory.Clear()'
$items = Method 'AICF_LoadoutEditor.c' 'Items'
Require 'LOADOUT_CATALOG_MODES' $items 'mode = m_iTargetMode.*m_Catalog.List\(category, m_aItems, mode, m_aSources\[m_iSourceIndex\]\)' 'm_iTargetMode'
Require 'LOADOUT_CATALOG_SOURCE' $items 'm_Catalog.List\(category, m_aItems, mode, m_aSources\[m_iSourceIndex\]\)' 'm_aSources[m_iSourceIndex]'
$capacityFilter = 'CanInsertResourceInStorage|CanInsertItemInStorage|CanReplaceItem'
Assert-AICFNotContains $failures 'LOADOUT_CATALOG_INDEPENDENT_OF_CAPACITY' $items $capacityFilter 'Каталог контейнера не фильтруется по заполненности; native compatibility ограничена обвесами'
if (($items + ' manager.CanInsertResourceInStorage(prefab, storage, slot);') -notmatch $capacityFilter) {
    $failures.Add('[LOADOUT_CATALOG_INDEPENDENT_OF_CAPACITY] Отрицательная копия не отклонена')
}
$negativeCount++
Require 'LOADOUT_CARD_BUDGET' (Method 'AICF_LoadoutItemGrid.c' 'Create') 'i < columns \* rows.*SetMaxFPS\(5\).*SetResolutionScale\(0.5, 0.5\)' 'i < columns * rows'
Require 'LOADOUT_CARDS_DETACH_BEFORE_REBUILD' (Method 'AICF_LoadoutEditor.c' 'Rebuild') 'm_Slots.ReleasePreviews\(\).*m_Items.ReleasePreviews\(\).*m_Draft.Build' 'm_Items.ReleasePreviews()'
Require 'LOADOUT_CARDS_DETACH_BEFORE_CLOSE' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_Slots.Close\(\).*m_Items.Close\(\).*m_Draft.Clear' 'm_Items.Close()'
Require 'LOADOUT_CARD_SELECTION_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_Slots.m_OnSelected.Remove\(OnCardSelected\).*m_Items.m_OnSelected.Remove\(OnCardSelected\)' 'm_Items.m_OnSelected.Remove(OnCardSelected)'
Require 'LOADOUT_CARD_NATIVE_RELEASE' (Method 'AICF_LoadoutItemGrid.c' 'ReleasePreviews') 'Remove\(Render\).*SetVisible\(false\).*SetPreviewItem\(card.m_Preview, null\).*m_Manager = null' 'SetPreviewItem(card.m_Preview, null)'
Require 'LOADOUT_CARD_DEFER_BIND' (Method 'AICF_LoadoutItemGrid.c' 'SetItems') 'ReleasePreviews\(\).*ResolveThumbnailManager\(\).*CallLater\(Render, 1, false\)' 'CallLater(Render, 1, false)'
Require 'LOADOUT_CARD_CLIENT_MANAGER' (Method 'AICF_LoadoutItemGrid.c' 'ResolveThumbnailManager') 'RplMode.Dedicated.*GetGame\(\).GetWorld\(\).*world.GetItemPreviewManager\(\)' 'world.GetItemPreviewManager()'
Require 'LOADOUT_CARD_ALPHA_BLEND' (Method 'AICF_LoadoutItemGrid.c' 'Create') 'SetBlendMode\(RenderTargetWidgetBlendMode.ALPHA_BLEND\)' 'SetBlendMode(RenderTargetWidgetBlendMode.ALPHA_BLEND)'
Require 'LOADOUT_SLOT_NATIVE_AREA' (Method 'AICF_LoadoutSlotView.c' 'Describe') 'LoadoutSlotInfo.Cast\(storage.GetSlot\(slot\)\).*info.GetAreaType\(\).*LoadoutHeadCoverArea' 'info.GetAreaType()'
Require 'LOADOUT_SLOT_CONTEXT' (Method 'AICF_LoadoutEditor.c' 'OnCardSelected') 'grid == m_Slots.*CallLater\(FocusSlotCatalog, 350, false\)' 'CallLater(FocusSlotCatalog, 350, false)'
Require 'LOADOUT_ARMOR_CONTEXT' $items 'm_ItemAreas.Filter\(m_aItems, m_TargetArea, m_Draft.GetPreview\(\)\)' 'm_TargetArea'
Require 'LOADOUT_WEAPON_CONTEXT' $items 'm_bWeaponTarget.*FilterWeapons\(m_aItems, m_sTargetWeaponType' 'm_sTargetWeaponType'
Require 'LOADOUT_NATIVE_WEAPON_SLOT' (Method 'AICF_LoadoutSlotView.c' 'WeaponSlot') 'FindComponents\(WeaponSlotComponent, components\).*GetSlotInfo\(\) == storage.GetSlot\(slot\)' 'GetSlotInfo() == storage.GetSlot(slot)'
Require 'LOADOUT_HIDE_INTERNAL_WEAPON_SLOT' (Method 'AICF_LoadoutSlotView.c' 'VisibleSlot') 'GetWeaponSlotIndex\(\) < SCR_InventoryMenuUI.WEAPON_SLOTS_COUNT' 'GetWeaponSlotIndex() < SCR_InventoryMenuUI.WEAPON_SLOTS_COUNT'
Require 'LOADOUT_OPEN_DOUBLE_CLICK' (Method 'AICF_LoadoutEditor.c' 'OnSlotActivated') 'm_bPending.*!m_bDraftReady.*grid != m_Slots.*OpenContainer\(\)' 'OpenContainer()'
Require 'LOADOUT_REMOVE_RIGHT_CLICK' (Method 'AICF_LoadoutEditor.c' 'OnSlotRemoved') 'm_bPending.*!m_bDraftReady.*grid != m_Slots.*ApplySelection\(true\)' 'ApplySelection(true)'
Require 'LOADOUT_RIGHT_CLICK_GATE' (Method 'AICF_LoadoutItemGrid.c' 'OnMouseButtonUp') 'SCR_EMouseButtons.RIGHT.*!m_bEnabled.*index >= m_aPrefabs.Count\(\).*m_OnRemoved.Invoke' '!m_bEnabled'
Require 'LOADOUT_RIGHT_CLICK_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_OnRemoved.Remove\(OnSlotRemoved\)' 'm_OnRemoved.Remove(OnSlotRemoved)'
Require 'LOADOUT_DEFERRED_FOCUS_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'Remove\(FocusSlotCatalog\)' 'Remove(FocusSlotCatalog)'
Require 'LOADOUT_NATIVE_CHILD_IDENTITY' (Method 'AICF_LoadoutNavigation.c' 'Child') 'CoveringItem.*child.m_Owner == item' 'child.m_Owner == item'
Require 'LOADOUT_NATIVE_ITEM_TRAVERSAL' (Method 'AICF_LoadoutNavigation.c' 'Collect') 'storage.GetItem\(slot\).*GetParentSlot\(\).GetStorage\(\) != storage.*GetParentSlot\(\).GetID\(\) != slot' 'GetParentSlot().GetStorage() != storage'
Require 'LOADOUT_ROOT_BOTH_KINDS' (Method 'AICF_LoadoutNavigation.c' 'Rows') 'EquipedLoadoutStorageComponent.Cast.*EquipedWeaponStorageComponent.Cast' 'EquipedWeaponStorageComponent.Cast'
Require 'LOADOUT_NATIVE_ITEM_LABEL' (Method 'AICF_LoadoutCatalog.c' 'EntityName') 'GetUIInfo\(\).*WidgetManager.Translate\(item.GetUIInfo\(\).GetName\(\)\)' 'WidgetManager.Translate(item.GetUIInfo().GetName())'
Assert-AICFNotContains $failures 'LOADOUT_NO_DOUBLE_REMOVE' (Method 'AICF_LoadoutEditor.c' 'OnSlotActivated') 'ApplySelection' 'Двойной клик только открывает предмет'
Assert-AICFNotContains $failures 'LOADOUT_NO_REDUNDANT_CONTROLS' (Method 'AICF_LoadoutEditor.c' 'Create') 'Button\("(inside|delete)"|m_Storage = Combo' 'Навигация через основной список; удаление по ПКМ'
Require 'LOADOUT_REMOVE_ACTIVATION_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_Slots.m_OnActivated.Remove\(OnSlotActivated\)' 'm_Slots.m_OnActivated.Remove(OnSlotActivated)'
Require 'LOADOUT_APPEARANCE_LOCAL_ONLY' (Method 'AICF_LoadoutInventory.c' 'KeepAppearance') 'GetWorld\(\) == GetGame\(\).GetWorld\(\).*visual.SetHead\(m_sHead\).*visual.SetBody\(m_sBody\).*component.CommitChanges\(\)' 'GetWorld() == GetGame().GetWorld()'
$editorRecord = $records | Where-Object Name -eq 'AICF_LoadoutEditor.c'
Require 'LOADOUT_CONTENT_CATEGORY_SCOPE' (Method 'AICF_LoadoutEditor.c' 'Selection') 'm_bContentFilter = location && !location.m_sPath.IsEmpty\(\) && !AICF_LoadoutSlotView.HasFixedSlots.*m_wCatalogContext.SetVisible\(!m_bContentFilter\).*GetRootWidget\(\).SetVisible\(m_bContentFilter\)' '!location.m_sPath.IsEmpty()'
Require 'LOADOUT_CLOTH_ATTACHMENT_SLOTS' (Method 'AICF_LoadoutSlotView.c' 'HasFixedSlots') 'WeaponAttachmentsStorageComponent.Cast.*LoadoutSlotInfo.Cast\(storage.GetSlot\(i\)\)' 'LoadoutSlotInfo.Cast(storage.GetSlot(i))'
Require 'LOADOUT_MULTIAREA_METADATA' (Method 'AICF_LoadoutClothing.c' 'Covers') 'GetAreaType\(\).Type\(\).IsInherited\(area\).*GetBlockedSlots\(blocked\)' 'GetBlockedSlots(blocked)'
Require 'LOADOUT_ARMOR_PARTITION_PRESERVED' (Method 'AICF_LoadoutSlotView.c' 'MatchesArea') 'actual.IsInherited\(area\).*area != LoadoutJacketArea && area != LoadoutPantsArea.*return false' 'area != LoadoutJacketArea && area != LoadoutPantsArea'
Require 'LOADOUT_MULTIAREA_PRIMARY' (Method 'AICF_LoadoutClothing.c' 'TargetSlot') 'Covers\(cloth, Area\(storage, requested\)\).*GetSlotFromArea\(cloth.GetAreaType\(\).Type\(\)\)' 'GetSlotFromArea(cloth.GetAreaType().Type())'
Require 'LOADOUT_MULTIAREA_CONFLICTS_LOCAL' (Method 'AICF_LoadoutClothing.c' 'RemoveConflictsLocal') 'GetWorld\(\) == GetGame\(\).GetWorld\(\).*Covers\(cloth, area\) && Covers\(existing, area\).*DeleteLocal\(conflictItem\)' 'Covers(existing, area)'
Require 'LOADOUT_MULTIAREA_REPLAY' $replay 'TargetSlot\(storage, slot, candidateItem\).*RemoveConflictsLocal\(storage, candidateItem\).*slot = targetSlot' 'RemoveConflictsLocal(storage, candidateItem)'
Require 'LOADOUT_MULTIAREA_RESTORE_ORDER' $restore 'rpl.IsMaster\(\).*ClearForRestore\(entity, manager\).*ApplyEntityStorageString' 'ClearForRestore(entity, manager)'
Require 'LOADOUT_MULTIAREA_RESTORE_AUTHORITY' (Method 'AICF_LoadoutClothing.c' 'ClearForRestore') '!Replication.IsServer\(\).*controller.IsPlayerControlled\(\).*!rpl.IsMaster\(\).*manager.TryDeleteItem' '!rpl.IsMaster()'
Require 'LOADOUT_CONTENT_CATEGORY_FILTER' $items 'if \(m_bContentFilter\).*category = m_aContentTypes\[filter\].*mode = m_aContentModes\[filter\]' 'mode = m_aContentModes[filter]'
Require 'LOADOUT_ATTACHMENT_FILTER' $items 'if \(m_bAttachmentTarget\).*FilterAttachments\(m_aItems, location.m_Storage, m_aSlots\[m_Slots.GetSelected\(\)\]' 'if (m_bAttachmentTarget)'
$attachments = Method 'AICF_LoadoutSlotView.c' 'MatchesAttachment'
$magazine = Method 'AICF_LoadoutMagazines.c' 'Compatible'
Require 'LOADOUT_SPARE_CATALOG' $magazine '!catalog.Allows\(prefab\)' '!catalog.Allows(prefab)'
Require 'LOADOUT_SPARE_LOCAL_WORLD' $magazine 'preview.GetWorld\(\) == GetGame\(\).GetWorld\(\).*muzzle.GetOwner\(\).GetWorld\(\) == GetGame\(\).GetWorld\(\).*candidate.GetWorld\(\) != muzzle.GetOwner\(\).GetWorld\(\)' 'candidate.GetWorld() != muzzle.GetOwner().GetWorld()'
Require 'LOADOUT_SPARE_MAGAZINE_WELL' $magazine 'magazine.GetMagazineWell\(\).Type\(\) == muzzle.GetMagazineWell\(\).Type\(\)' 'magazine.GetMagazineWell().Type() == muzzle.GetMagazineWell().Type()'
$destination = Method 'AICF_LoadoutMagazines.c' 'Destination'
Require 'LOADOUT_SPARE_POCKETS' $destination '!SCR_UniversalInventoryStorageComponent.Cast\(location.m_Storage\).*HasFixedSlots\(location.m_Storage\)' '!SCR_UniversalInventoryStorageComponent.Cast(location.m_Storage)'
Require 'LOADOUT_SPARE_ADDRESS' $destination 'ResolvePath\(manager.GetOwner\(\), location.m_sPath\) != location.m_Owner' 'ResolvePath(manager.GetOwner(), location.m_sPath) != location.m_Owner'
Require 'LOADOUT_SPARE_CAPACITY' $destination 'manager.CanInsertResourceInStorage\(prefab, target.m_Storage, -1\)' 'manager.CanInsertResourceInStorage(prefab, target.m_Storage, -1)'
$addMagazine = Method 'AICF_LoadoutEditor.c' 'AddMagazine'
Require 'LOADOUT_SPARE_PENDING' $addMagazine 'm_bPending \|\| !m_Recipe \|\| !m_bDraftReady' 'm_bPending || '
Require 'LOADOUT_SPARE_OPERATION_BOUND' $addMagazine 'm_Recipe.m_aPaths.Count\(\) >= AICF_LoadoutRecipe.MAX_OPERATIONS' 'm_Recipe.m_aPaths.Count() >= AICF_LoadoutRecipe.MAX_OPERATIONS'
Require 'LOADOUT_SPARE_RECIPE' $addMagazine 'm_Recipe.Add\(destination.m_sPath, destination.m_sStorage, -1, prefab, 1\)' 'm_Recipe.Add(destination.m_sPath, destination.m_sStorage, -1, prefab, 1)'
Require 'LOADOUT_SPARE_ROLLBACK' $addMagazine 'if \(!Rebuild\(\)\).*m_Recipe.Undo\(\).*Rebuild\(\)' 'm_Recipe.Undo()'
Assert-AICFNotContains $failures 'LOADOUT_SPARE_NO_REFRESH_SCAN' (Method 'AICF_LoadoutEditor.c' 'UpdateActions') 'LoadoutMagazines.Resolve|ResolvePreviewEntityForPrefab' 'Подбор магазина выполняется только по действию пользователя'
Assert-AICFNotContains $failures 'LOADOUT_SPARE_READ_ONLY' ($magazine + $destination + (Method 'AICF_LoadoutMagazines.c' 'Resolve')) '\.(AttachEntity|DetachEntity|SetAmmoCount|Try\w*)\(' 'Подбор не меняет заряженный магазин или инвентарь'
Require 'LOADOUT_ATTACHMENT_LOCAL_ONLY' $attachments 'world == GetGame\(\).GetWorld\(\).*preview.GetWorld\(\) == GetGame\(\).GetWorld\(\).*manager.GetOwner\(\).GetWorld\(\) != world.*candidate.GetWorld\(\) != world' 'world == GetGame().GetWorld()'
Require 'LOADOUT_ATTACHMENT_NATIVE_SLOT' $attachments 'GetParentContainer\(\).*attachment.CanSetAttachment\(candidate\)' 'attachment.CanSetAttachment(candidate)'
Require 'LOADOUT_ATTACHMENT_OCCUPIED' $attachments 'if \(storage.Get\(slot\)\).*manager.CanReplaceItem\(candidate, storage, slot\).*manager.CanInsertItemInStorage\(candidate, storage, slot\)' 'manager.CanReplaceItem(candidate, storage, slot)'
Assert-AICFNotContains $failures 'LOADOUT_ATTACHMENT_READ_ONLY' $attachments '\.(AttachEntity|DetachEntity|SetAttachment|Try\w*)\(' 'Фильтр не меняет инвентарь для проверки совместимости'
Require 'LOADOUT_MAGAZINE_SLOT_CATALOG' (Method 'AICF_LoadoutSlotView.c' 'AttachmentCatalog') 'BaseMuzzleComponent.Cast.*category = 0;.*mode = SCR_EArsenalItemMode.AMMUNITION' 'mode = SCR_EArsenalItemMode.AMMUNITION'
Require 'LOADOUT_FILTER_FOCUS_PRESERVED' (Method 'AICF_LoadoutEditor.c' 'FocusSlotCatalog') 'if \(focus != m_sCatalogFocus\).*m_wSearch.SetText' 'if (focus != m_sCatalogFocus)'
Require 'LOADOUT_FILTER_RESET' ((Get-AICFMethodBody $editorRecord 'OnClick') -replace '\s+', ' ') 'action == "clearFilters".*m_wSearch.SetText\(""\).*m_ContentCategory.SetCurrentItem\(0, false, false, false\)' 'm_ContentCategory.SetCurrentItem(0, false, false, false)'
Require 'LOADOUT_ODD_GRID_LAST_ROW' (Method 'AICF_LoadoutItemGrid.c' 'LastPageOffset') 'Math.Ceil\(itemCount / \(float\)columns\)' '(float)columns'
Require 'LOADOUT_GRID_SCROLL_PRESERVED' (Method 'AICF_LoadoutItemGrid.c' 'SetItems') 'preserveScroll.*prefabs\[i\] != m_aPrefabs\[i\].*if \(!unchanged\).*m_iFirst = 0' 'if (!unchanged)'
Require 'LOADOUT_GRID_NO_SELECTION_JUMP' $items 'sameItems = m_Items.SetItems\(m_aItems, names, details, true\).*m_Items.Select\(m_aItems.Find\(previous\), !sameItems\)' '!sameItems'
Require 'LOADOUT_GRID_EMPTY_STATE' (Method 'AICF_LoadoutItemGrid.c' 'Render') 'm_Empty.SetVisible\(m_aPrefabs.IsEmpty\(\)\)' 'm_Empty.SetVisible(m_aPrefabs.IsEmpty())'
Require 'LOADOUT_AREA_METADATA_CACHE' (Method 'AICF_LoadoutSlotView.c' 'Get') 'm_Areas.Find\(prefab, area\).*ResolvePreviewEntityForPrefab.*GetWorld\(\) == GetGame\(\).GetWorld\(\).*m_Areas.Insert' 'm_Areas.Find(prefab, area)'
$gridRecord = $records | Where-Object Name -eq 'AICF_LoadoutItemGrid.c'
Assert-AICFNotContains $failures 'LOADOUT_CARD_NO_MUTABLE_DRAFT' $gridRecord.Code 'array<IEntity>|ResolvePreviewEntityForPrefab|m_Draft|delete m_Manager' 'Миниатюры используют prefab-only cache штатного UI; черновик остаётся изолированным'
Assert-AICFNotContains $failures 'LOADOUT_CARD_SRGB_PALETTE' (Method 'AICF_LoadoutItemGrid.c' 'RefreshColors') 'Color.FromInt' 'Палитра карточек использует тот же SRGBA путь, что и панель'
Require 'LOADOUT_PREVIEW_FAILURE_VISIBLE' (Method 'AICF_LoadoutEditor.c' 'Refresh') 'if \(!Rebuild\(\)\) status =' '!Rebuild()'
Require 'LOADOUT_IDLE_ROTATION' (Method 'AICF_LoadoutEditor.c' 'RotatePreview') 'if \(x == m_iMouseX && y == m_iMouseY\) return;' 'if (x == m_iMouseX && y == m_iMouseY) return;'
Require 'LOADOUT_ACTIVATION_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_OnActivated.Remove\(OnItemActivated\)' 'm_OnActivated.Remove(OnItemActivated)'
Require 'LOADOUT_DOUBLE_CLICK_GATE' (Method 'AICF_LoadoutItemGrid.c' 'OnDoubleClick') '!m_bEnabled.*SCR_EMouseButtons.LEFT.*index >= m_aPrefabs.Count\(\).*m_OnActivated.Invoke' '!m_bEnabled'
Require 'LOADOUT_ACTIVATION_SHARED_APPLY' (Method 'AICF_LoadoutEditor.c' 'OnItemActivated') 'grid != m_Items.*ApplySelection\(false\)' 'ApplySelection(false)'
Require 'LOADOUT_APPLY_PENDING_GATE' (Method 'AICF_LoadoutEditor.c' 'ApplySelection') 'm_bPending \|\| !m_Recipe \|\| !m_bDraftReady' 'm_bPending || '
Require 'LOADOUT_SAVE_CHANGED_AND_VALID' (Method 'AICF_LoadoutEditor.c' 'OnClick') '!HasDraftChanges\(\) \|\| !HasValidName\(\) \|\| m_Player.AICF_LoadoutRevision\(\) != m_iRevision.*Request\(1, m_Recipe.Encode\(\)\)' '!HasDraftChanges() || '
Require 'LOADOUT_DIRTY_TARGET_RESET' (Method 'AICF_LoadoutEditor.c' 'SelectTarget') 'm_sAppliedData = string.Empty; m_sDraftData = string.Empty;' 'm_sDraftData = string.Empty;'
Require 'LOADOUT_NAME_INPUT_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'if \(m_wName\) m_wName.RemoveHandler\(this\)' 'm_wName.RemoveHandler(this)'
Require 'LOADOUT_APPLY_ROLLBACK' (Method 'AICF_LoadoutEditor.c' 'ApplySelection') 'if \(!Rebuild\(\)\).*m_Recipe.Undo\(\).*Rebuild\(\)' 'm_Recipe.Undo()'
Require 'LOADOUT_CAPACITY_NATIVE' (Method 'AICF_LoadoutSlotView.c' 'Capacity') 'GetOwnedStorages\(pockets, 1, false\).*GetOccupiedSpace\(\).*GetMaxVolumeCapacity\(\)' 'GetOwnedStorages(pockets, 1, false)'
Require 'LOADOUT_VIEW_CLEANUP' (Method 'AICF_LoadoutEditor.c' 'Close') 'm_wRoot.RemoveFromHierarchy\(\).*m_Preview.Clear\(\)' 'm_Preview.Clear()'
Require 'LOADOUT_NO_GAMEPLAY_RENDER' (Method 'AICF_LoadoutEditor.c' 'Rebuild') 'm_wPreview.SetVisible\(false\).*m_wPreview.SetWorld.*m_wPreview.SetVisible\(true\)' 'm_wPreview.SetWorld(m_Preview.GetWorld(), 0)'
$rect = Method 'AICF_StrategicUI.c' 'CreateRect'
Require 'LOADOUT_BACKGROUND_INPUT_TRANSPARENCY' $rect 'background.SetFlags\(WidgetFlags.VISIBLE \| WidgetFlags.IGNORE_CURSOR' 'background.SetFlags(WidgetFlags.VISIBLE | WidgetFlags.IGNORE_CURSOR'
Require 'LOADOUT_BACKGROUND_COLOR_VALUE' $rect 'backgroundColor = color.PackToInt\(\).*background.SetColor\(Color.FromInt\(backgroundColor\)\)' 'background.SetColor(Color.FromInt(backgroundColor))'
Require 'LOADOUT_BACKGROUND_LAYER' $rect 'background.SetZOrder\(0\).*inputWidget.SetZOrder\(1\)' 'background.SetZOrder(0)'
Require 'LOADOUT_LOCAL_LIGHTS' (Method 'AICF_LoadoutPreview.c' 'Build') 'm_Lighting = GetGame\(\).SpawnEntityPrefabLocal\(lighting, m_World\).*if \(!HasLighting\(\)\)' 'if (!HasLighting())'
Require 'LOADOUT_LIGHTS_CLEANUP' (Method 'AICF_LoadoutPreview.c' 'Clear') 'DeleteEntityAndChildren\(m_Lighting\).*m_Lighting = null.*m_WorldRef = null' 'DeleteEntityAndChildren(m_Lighting)'
$fill = Method 'AICF_LoadoutPreview.c' 'CreateFillLight'
Require 'LOADOUT_FILL_OWN_WORLD' $fill 'SpawnEntityPrefabLocal\(resource, m_World\).*entity.GetWorld\(\) != m_World.*DeleteEntityAndChildren\(entity\)' 'entity.GetWorld() != m_World'
Require 'LOADOUT_FILL_NO_SHADOW_PASS' $fill 'SetCastShadow\(false\)' 'SetCastShadow(false)'
Require 'LOADOUT_FILL_CLEANUP' (Method 'AICF_LoadoutPreview.c' 'Clear') 'DeleteEntityAndChildren\(m_FillLight\).*m_FillLight = null.*m_WorldRef = null' 'DeleteEntityAndChildren(m_FillLight)'
$fillUpdate = Method 'AICF_LoadoutPreview.c' 'UpdateFillLight'
Require 'LOADOUT_FILL_ENTITY_ORIENTATION' $fillUpdate 'DirectionAndUpMatrix\(direction, camera\[1\], lightTransform\).*lightTransform\[3\] = position.*SetWorldTransform\(lightTransform\).*m_FillLight.Update\(\)' 'SetWorldTransform(lightTransform)'
Assert-AICFNotContains $failures 'LOADOUT_NO_FILL_REBUILD_ON_INPUT' (Method 'AICF_LoadoutPreview.c' 'UpdateFillLight') 'SpawnEntity|CreateLight|Resource.Load' 'Input меняет transform существующего света'
Assert-AICFNotContains $failures 'LOADOUT_NO_FILL_REQUIRED_FOR_MODEL' (Method 'AICF_LoadoutPreview.c' 'IsReady') 'HasFillLight|m_FillLight' 'При недоступной дополнительной подсветке остаётся stock scene'
$previewRecord = $records | Where-Object Name -eq 'AICF_LoadoutPreview.c'
$nativePointerField = '\bLightHandle\s+m_\w+'
Assert-AICFNotContains $failures 'LOADOUT_NO_NATIVE_POINTER_FIELDS' $previewRecord.Code $nativePointerField 'LightHandle допускается только как локальная переменная'
$invalidField = $previewRecord.Code + ' protected LightHandle m_InvalidLight;'
if ($invalidField -notmatch $nativePointerField) { $failures.Add('[LOADOUT_NO_NATIVE_POINTER_FIELDS] Отрицательная копия не отклонена') }
$negativeCount++
Assert-AICFNotContains $failures 'LOADOUT_NO_ROTATION_REBUILD' (Method 'AICF_LoadoutEditor.c' 'RotatePreview') 'SetPreviewItem|\.Build\(' 'Вращение меняет только камеру'
Require 'LOADOUT_SAVE_ACK' (Method 'AICF_LoadoutEditor.c' 'Refresh') 'AICF_LoadoutToken\(\) == m_iToken.*AICF_LoadoutAccepted\(\)' 'AICF_LoadoutAccepted()'
Require 'LOADOUT_DEPLOYMENT_REVISION' (Method 'AICF_GroupSlot.c' 'ApplyDeploymentLoadouts') '!IsDeploymentLoadoutCurrent\(\)' '!IsDeploymentLoadoutCurrent()'
foreach ($spawn in @('BeginInitialSpawn', 'BeginReplacementSpawn')) {
    Require "LOADOUT_$spawn" (Method 'AICF_GroupSlot.c' $spawn) 'm_iDeploymentLoadoutRevision = m_iLoadoutRevision;.*m_iSpawnGeneration\+\+' 'm_iDeploymentLoadoutRevision = m_iLoadoutRevision;'
}
$tick = Method 'AICF_InfantryRecruitmentService.c' 'Tick'
Require 'LOADOUT_RECRUIT_BASE_PRICE' $tick 'order.m_iCost = m_Config.Cost\(order.m_sRole\);' 'order.m_iCost = m_Config.Cost(order.m_sRole);'
$recruitment = ($records | Where-Object Name -eq 'AICF_InfantryRecruitmentService.c').Code
Assert-AICFNotContains $failures 'LOADOUT_RECRUIT_NO_SURCHARGE' $recruitment '(loadout|binding).m_iCost|order.m_iCost\s*\+=' 'Комплект не меняет выбор казармы или цену роли'
$economy = ($records | Where-Object Name -eq 'AICF_EconomySystem.c').Code
Assert-AICFNotContains $failures 'LOADOUT_REPLACEMENT_NO_SURCHARGE' $economy 'GetDeploymentLoadoutCost\(' 'Цена, pacing и reservation replacement не зависят от экипировки'
foreach ($negative in @(
    @($recruitment + ' cost += binding.m_iCost;', '(loadout|binding).m_iCost|order.m_iCost\s*\+='),
    @($economy + ' slot.GetDeploymentLoadoutCost();', 'GetDeploymentLoadoutCost\(')
)) {
    if ($negative[0] -notmatch $negative[1]) { $failures.Add('[LOADOUT_NO_SURCHARGE] Отрицательная копия не отклонена') }
    $negativeCount++
}
Require 'LOADOUT_RECRUIT_REVISION' $tick 'order.m_iLoadoutRevision != order.m_Slot.GetLoadoutRevision\(\)' 'order.m_iLoadoutRevision != order.m_Slot.GetLoadoutRevision()'
Require 'LOADOUT_RECRUIT_BEFORE_DEBIT' $tick 'HasExactFactionRoster.*AICF_LoadoutApplicator.Apply.*DebitInfantryRecruit.*RefundInfantryRecruit' 'AICF_LoadoutApplicator.Apply'
Require 'LOADOUT_SPAWN_INDEX' (Method 'AICF_LoadoutMemberIdentity.c' 'SpawnGroupMember') 'super.SpawnGroupMember.*!before.Contains\(agent\).*added == 1.*m_aUnitPrefabSlots\[index\] == res' 'added == 1'
foreach ($record in $records | Where-Object { $_.Name -like 'AICF_Loadout*' }) {
    Assert-AICFNotContains $failures 'LOADOUT_NO_RAW_SERIALIZER' $record.Code 'ApplyLoadoutString\(' 'Внешний payload не является stock snapshot'
    if ($record.Name -like '*Probe*') { $failures.Add('[LOADOUT_FIXTURE_IN_PRODUCTION] Удалить временный probe') }
}
if ($failures.Count) {
    $failures | ForEach-Object { Write-Output "[AICF][LOADOUT_STATIC][FAIL] $_" }
    exit 1
}
Write-Output "[AICF][LOADOUT_STATIC][PASS] negative_cases=$negativeCount authority=PASS identity=PASS inventory=PASS persistence=PASS lifecycle=PASS"
exit 0
